### ISSUE TITLE
Consider releasing FCOS with a predictable release cadence

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#1062]
**Describe the enhancement**

As the release process matures, we now have regular releases going out approximately every two weeks.

I think that the next step is to move to a predictable release cadence:

- Start the release process on Tuesday/Friday.
- Plan the rollout for Tuesday at a given (early in the day) fixed time.

Doing this does not prevent us from making ad-hoc releases when needed.

This would make FCOS release behave more like Firefox, Chrome, Rust, etc. releases that go out on a predictable X weeks cadence.

The main benefit here is making Fedora CoreOS releases even less surprising. Right now, users/admins don't know when a release will happen and when it will be deployed. They can set update windows with Zincati but doing that means that they might miss a release by a couple of hours for example depending on when they decide to place their window.

Having a pre-agreed upon time for releases makes it easier for users/admin to plan for testing, investigation and bug reporting time for each new testing release.

Having new releases consistently happen on Tuesday will also mean that if any bug where to slip into a release, it is most probable that users/admins will be available and able to dedicate time to it rather than if this happens on a Friday or weekend.

**Comment by dustymabe** [comment]
I think the only way to do this (more predictable release day/time) reliably is to stage/prep the builds the week before. Let's say we did the build on Thursday of the previous week. We pay a 6 day penalty (older content). Is it worth it? 

I don't think what we have now is all that bad and we'll never be completely predictable because of ad-hoc releases.

**Comment by bgilbert** [comment]
Since we'll never be completely predictable, I actually think there's value in remaining somewhat inconsistent, so we don't set incorrect expectations.  The FCOS philosophy implies that users shouldn't need to carefully track releases anyway; `testing` nodes should be deployed in a way that doesn't break workloads (e.g. in a staging cluster, or as one replica in a prod cluster).

**Comment by travier** [comment]
Let's drop this one from the meeting rotation. It's not a priority and we have other things going on.

**Comment by dustymabe** [comment]
We discussed this in the [meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/LPL4NCX4VFMNMAWGRSMD77M3TSRSCUOX/).

```
12:14:01    dustymabe | #agreed We try to release every two weeks and we try to
                      | have releases go out on Tuesday. We don't want to write
                      | down any more contraints for ourselves than that so we
                      | don't waste time with the details and focus on other work.
```

**Comment by bgilbert** [comment]
Given https://github.com/coreos/fedora-coreos-tracker/issues/1062#issuecomment-1057283654, should we close this out?

**Comment by travier** [comment]
Let's close this one. 🙂
