### ISSUE TITLE
podman v4.0, Fedora 35 and CoreOS

### ISSUE THREAD

**Issue by lsm5** [coreos/fedora-coreos-tracker#1070]
Podman v4.0 is going to be a breaking change release. That implies we can't ship podman v4.0 in Fedora 35 and older.

In case FCoS 35 and older wants to use podman v4.0, we would like to know how to make podman updates available.

@mheon @baude @rhatdan @dustymabe @cgwalters

**Comment by cgwalters** [comment]
As I understand it, we now actually have a circular relationship between podman and FCOS because `podman machine` pulls down a FCOS build for the case of e.g. running `podman` on Mac OS.

And then, podman 4 and podman 3 have incompatible remoting APIs, so we need to have the same version both client and server.

This is quite a gordian knot to cut.  My instinct here is that what may be simplest is for podman4 to carry code that detects the case where podman v3 is in the FCOS image, and uses e.g. `rpm-ostree override replace` to pull down a podman4 build.

**Comment by cgwalters** [comment]
A side note: https://fedoraproject.org/wiki/Changes/OstreeNativeContainer will make it so that this override flow could actually be "podman ships a container image on quay.io which is FROM quay.io/fedora/coreos && RUN dnf copr enable podman4 && dnf -y update podman`", and then client side just pulls it.  Whether that's better or worse than doing overrides client side is another thing - different tradeoffs for sure.

**Comment by travier** [comment]
Could we get a little bit more details about the changes? I can only find https://github.com/containers/podman/releases/tag/v4.0.0-rc1 which doesn't have much details.

**Comment by dustymabe** [comment]
Added some of our `podman` friends to our community meeting for tomorrow so we can discuss more there.

**Comment by rhatdan** [comment]
I would prefer the image come from server side, if possible.  We can talk tomorrow.

**Comment by travier** [comment]
Independently of what we do for next, as this will be a breaking change, we should probably announce it to coreos-status approximately 3 months ahead of the planned F36 rebase for testing.

**Comment by jlebon** [comment]
This was discussed in [today's community meeting](https://meetbot-raw.fedoraproject.org/teams/fedora_coreos_meeting/fedora_coreos_meeting.2022-01-19-16.29.html):

```
12:15:46 < jlebon> #agreed we will ship podman v4 based on f35 in next for now and
                   meanwhile investigate other approaches before the beta rebase
```

**Comment by dustymabe** [comment]
> Independently of what we do for next, as this will be a breaking change, we should probably announce it to coreos-status approximately 3 months ahead of the planned F36 rebase for testing.

Which means we probably just need to send a communication in the next week that says podman 4.0 is coming to `next` and will be in `testing`/`stable` when the f36 rebase happens.

**Comment by travier** [comment]
What's the compatibility matrix between the client and the server for podman?

| | server v3 | server v4 |
|-|---------------|--------------|
| **client v3** | OK | ? |
| **client v4** | ? | OK |

If a podman v3 client can not talk to a podman v4 server, then shipping only podman v4 in next has another downside: it breaks existing next users of podman machine.

In Fedora CoreOS we try to avoid breaking changes and provide a graceful transition period when they are needed. So if podman does not provide a transition period for compatibility between the two versions, I think we should **ship both podman v3 and v4**.

We would have the packages directly available in Fedora 35 and thus later in FCOS next and testing, and then stable two weeks later. This would make it much easier to test podman v4 while keeping podman v3 compatibility by default.

This requires that both podman v3 and v4 are co-installable and that we figure out a way to configure a system to use podman v4 only on first boot via something that could be configured via Ignition. This could be a symlink for the units for example.

Fedora 36 would only get podman v4 and then when we rebase FCOS next to the F36 Beta, there would only be podman v4 remaining.

The only downside I can see here is that we increase the size of the FCOS image but that is only temporary for the transition. I think it's better to pay the cost in term of size than in terms of users with disrupted use cases.

**Comment by mheon** [comment]
If you fill your question marks with "no", you have the matrix - 3.0 can only talk to 3.0, 4.0 only to 4.0.

Regarding shipping 3 and 4 in parallel: I'd have to verify if 3.x and 4.0 can actually operate on the same machine using the same configuration sanely. There are some database schema changes made by 4.0 on upgrade. They don't prevent 3.x from being used afterwards, I've been using both in parallel extensively during development, but I think some networking configuration might have been rewritten such that port forwarding or static IP addresses (maybe some other things) might break if a user went from Podman v4 to Podman v3 (in the sense that the container would still run, but user-requested configuration like port mappings would not be applied by v3, only v4). If the intention is to allow them to be swapped in and out via a solution like `alternatives` and not to use both simultaneously this probably isn't an issue, as the breakage only occurs when moving between implementations, so people staying on the default would be fine.

**Comment by dustymabe** [comment]
> What's the compatibility matrix between the client and the server for podman?
> 	server v3 	server v4
> **client v3** 	OK 	?
> **client v4** 	? 	OK
> 
> If a podman v3 client can not talk to a podman v4 server, then shipping only podman v4 in next has another downside: it breaks existing next users of podman machine.

I think the podman team said yesterday in our meeting that podman machine users can choose which stream to target.

Also, they said they would only switch the default to `next` when they ship podman v4, which means (IIUC) that you'd only default to `next` if you have a podman v4 client already. 

Does that alleviate your concern?

> 
> In Fedora CoreOS we try to avoid breaking changes and provide a graceful transition period when they are needed. So if podman does not provide a transition period for compatibility between the two versions, I think we should **ship both podman v3 and v4**.

My understanding is that `next` is for experimental changes (like this one) and future software versions (i.e. early preview of next major Fedora release). According to [our docs](https://docs.fedoraproject.org/en-US/fedora-coreos/update-streams/):

```
The next stream represents the future. It will often be used to experiment
with new features and also test out rebases of our platform on top of the
next major version of Fedora. The content in the next stream will also
eventually filter down into testing and on to stable.
```

I would totally agree with your sentiment if we were proposing to make this change in `testing` (which implies putting the change in `stable` in the next two weeks), but that's not what is proposed.

> 
> We would have the packages directly available in Fedora 35 and thus later in FCOS next and testing, and then stable two weeks later. This would make it much easier to test podman v4 while keeping podman v3 compatibility by default.
> 
> This requires that both podman v3 and v4 are co-installable and that we figure out a way to configure a system to use podman v4 only on first boot via something that could be configured via Ignition. This could be a symlink for the units for example.
> 
> Fedora 36 would only get podman v4 and then when we rebase FCOS next to the F36 Beta, there would only be podman v4 remaining.
> 
> The only downside I can see here is that we increase the size of the FCOS image but that is only temporary for the transition. I think it's better to pay the cost in term of size than in terms of users with disrupted use cases.

The other large downside (other than image size, which I agree is not a huge concern) is the time and effort invested to make all of that work. I just don't see it being worth the effort.

I do think that we should probably make the "override" proposal work as well just in case something breaks in `next` a user can select `testing` or `stable` and still get a working `podman machine`. The penalty they pay is the extra time for bringup.

**Comment by travier** [comment]
> If the intention is to allow them to be swapped in and out via a solution like alternatives and not to use both simultaneously this probably isn't an issue, as the breakage only occurs when moving between implementations, so people staying on the default would be fine.

Yes, my suggestion is more about choosing one or the other on first boot and then sticking with it for the entire lifetime of the system. I don't think we should support alternating between versions. Even though the current support for alternatives in FCOS is manual/partial, this could work in this case.

> I think the podman team said yesterday in our meeting that podman machine users can choose which stream to target.
> Also, they said they would only switch the default to next when they ship podman v4, which means (IIUC) that you'd only default to next if you have a podman v4 client already.

- I'm a podman machine v3 user, I switched to next for my FCOS machine. When FCOS switches next to podman v4, this no longer works.
- I'm a fresh podman machine v4 user, I have a bug in my FCOS next machine. When I switch to testing or stable it does not work too so I have no options.
  Moreover, when we rebase next to Fedora 36 Beta, I get a lot of unstable software and thus more chances that things break. I can not use a stable FCOS system with podman v4 until the Fedora 36 release.

I don't think having an "unstable" FCOS release as the base of the freshly released podman v4 will be a good publicity for podman.

> My understanding is that next is for experimental changes (like this one) and future software versions (i.e. early preview of next major Fedora release).

In this case, I think this is not a good use of next. To me, shipping RC kernels in next is perfectly fine. Kernels have to keep backward compatibility. Of course there will be unknown bugs, but the key word here is *unknown*.

Just like when we ship Fedora Beta in next. We have the CI in place to check Rawhide, the branched builds and we review the Fedora 36 changes. *Known* breakages are worked out in advance, before they reach next. When we rebase, we don't expect major issues.

In this case we *know* that it will break compatibility. So I don't think that this is a good way to spend our breakage or user-attention credit when we potentially have other options.

> The other large downside (other than image size, which I agree is not a huge concern) is the time and effort invested to make all of that work. I just don't see it being worth the effort.

If we can make the alternatives option work, this could be a reasonable amount of efforts.

More importantly, it keeps us aligned with what we have in Fedora, instead of having FCOS shipping packages that are not available in Fedora. Having podman v4 available as a non default option in Fedora 35 also enables others to try it out and report bugs.

Podman is a container runtime, the very base of FCOS, with systemd, the Kernel and rpm-ostree. I think that investing time into this component is probably a good use of our time given its value for FCOS.

**Comment by bgilbert** [comment]
> > In this case we _know_ that it will break compatibility. So I don't think that this is a good way to spend our breakage or user-attention credit when we potentially have other options.
> 
> Not sure I entirely agree. First it's in `next`. Second we aren't responsible completely for upstream software choosing to or not to make breaking changes. We should evaluate the changes and determine the impact, but in the end sometimes our users will have to take action.

`next` isn't `rawhide` though.  It's intended to run in production, just like the other streams; it'll just have a higher chance of accidental breakage.  We don't intentionally ship breakage to `next` without advance notice.  And as @travier points out, this isn't some incidental package, it's our recommended container engine.

**Comment by dustymabe** [comment]
> We don't intentionally ship breakage to `next` without advance notice.

Right. I imagine we'd communicate the change but not require a long notice period.



> And as @travier points out, this isn't some incidental package, it's our recommended container engine.

I see your point, but this could also be an argument for us wanting to ship it in `next` so we get more use of it and more feedback early so we can get issues fixed before shipping it in our other streams. Of course it needs to pass our CI before we'd ship it and if there are cases that break in real world usage that didn't break in CI we should use it as an opportunity to add test cases to our CI.

**Comment by travier** [comment]
> I see your point, but this could also be an argument for us wanting to ship it in next so we get more use of it and more feedback early so we can get issues fixed before shipping it in our other streams.

I don't think that's the way we should do that. This is **forcing** users to give us feedback when what we should do is **asking** them to try it in order to get feedback.

What we would be doing here is deprecating a version of the API of our **preferred container runtime** without a warning nor a transition period as the new API is not even available yet in any release. This is a really bad message to send to our community.

By making v4 co-available with v3 **on all streams**, we **enable** them to **decide** when they want to try it out in the next few months instead of pushing the change to them without warning. We will *force* the change when we switch to the Fedora 36 beta in next but at that point, there would have been a 2-3 months warning period where they could have given it a try.

If we switch Next to podman v4 now, we don't even have an option for users to try it out as there are no podman v4 **client** packages available in a Fedora stable release (not even in Rawhide) and not even as binary from the [release page](https://github.com/containers/podman/releases/tag/v4.0.0-rc1).

Moreover, we can not expect users to update all their servers at once thus we need to have an option for users to have both podman v3 and v4 **clients** co-installed on a system. The lack of backward compatibility for the podman v3 API in podman v4 makes it unpleasant as we can not use a single binary for both. Thus being able to **co-install v3 & v4 clients** on a stable Fedora system seems like a basic minimum to me.

At this point, as far as I understand, we are not really far from having the entire podman v3 & v4 stack co-installable on Fedora stable as most of the dependencies are either vendored into the binary or working with both versions.

Questions for @mheon @rhatdan @baude:
- Is it possible to make both podman v3 & v4 **clients** as co-installable packages in Fedora 35? As mentioned, we don't want users to use both locally but want them to be able to talk to both remote versions at the same time.
- How difficult would it be to have podman v4 **server** packages co-installable with v3 on Fedora 35 and decide on first boot which version to use?
- Maybe alternatives are a bad fit here and we should have podman v4 binaries and services named `podman4` in Fedora 35 and just `podman` in Fedora 36. This should make packaging easier.

Doing all of that also ensures that we have all streams supported for v3 & v4 when v4 is released. Thus we don't force podman machine v3 users to update to podman machine v4 until the Fedora 36 release. This gives them a transition period too. We also do not force podman machine v4 users to use next.

**Comment by travier** [comment]
Questions for @mheon @rhatdan @baude:
- Is it possible to make both podman v3 & v4 clients as co-installable packages in Fedora 35? As mentioned, we don't want users to use both locally but want them to be able to talk to both remote versions at the same time.
- How difficult would it be to have podman v4 server packages co-installable with v3 on Fedora 35 and decide on first boot which version to use?
- Maybe alternatives are a bad fit here and we should have podman v4 binaries and services named `podman4` in Fedora 35 and just `podman` in Fedora 36. This should make packaging easier.

**Comment by rhatdan** [comment]
> * Is it possible to make both podman v3 & v4 clients as co-installable packages in Fedora 35? As mentioned, we don't want users to use both locally but want them to be able to talk to both remote versions at the same time.
> 
Possible yes, but not going to happen in time.
> * How difficult would it be to have podman v4 server packages co-installable with v3 on Fedora 35 and decide on first boot which version to use?
> 
Very difficult.  Locations of Socket would be difficult to deal with.
> * Maybe alternatives are a bad fit here and we should have podman v4 binaries and services named `podman4` in Fedora 35 and just `podman` in Fedora 36? This would probably make packaging easier.
Still would not fix the socket issue. Also interoperability between other distros.

**Comment by travier** [comment]
The discussion moved to fedora-devel: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/4JRMF5IWBYZIOWG2UB2YVGXBWAQ36NMZ/

**Comment by dustymabe** [comment]
Thanks @travier. If we go that route I think remaining steps looks like:

- socialize with containers team for evaluation
- package review
- modify tests to test podman4 versus podman3

**Comment by cgwalters** [comment]
I have only superficially followed this discussion.  I suspect an area of bifurcation here is that (AFAIK) the `/usr/bin/podman` CLI is not changing in an incompatible way (is that correct?) and that means that podman4 will continue to work for people who are e.g. just running the CLI via systemd units and the like.  But OTOH nontrivial users speak the API.

Anyways, I am OK with the podman4 co-installable proposal.   (And thanks @travier for pushing that forward!)

But...would it be simpler to document how to get podman v4 (i.e. it's still `podman` in RPM terms, just version 4, not co-installable) via e.g. butane sugar that would use `rpm-ostree override replace`?  Or in theory, we could even ship the packages "pre-downloaded" but not actually installed so that enabling it wouldn't even touch the network (some things to do there rpm-ostree side, but definitely still tractable).

It does seem to me it'd be good to have whatever solution is settled on be common to Fedora, because it will almost certainly affect other use cases too outside of FCOS, from Workstation to Server.

**Comment by travier** [comment]
> But...would it be simpler to document how to get podman v4 (i.e. it's still `podman` in RPM terms, just version 4, not co-installable) via e.g. butane sugar that would use `rpm-ostree override replace`? Or in theory, we could even ship the packages "pre-downloaded" but not actually installed so that enabling it wouldn't even touch the network (some things to do there rpm-ostree side, but definitely still tractable).

We could definitely do that too but it would take longer to setup the system on first boot for podman machine users.

**Comment by jlebon** [comment]
> > But...would it be simpler to document how to get podman v4 (i.e. it's still `podman` in RPM terms, just version 4, not co-installable) via e.g. butane sugar that would use `rpm-ostree override replace`? Or in theory, we could even ship the packages "pre-downloaded" but not actually installed so that enabling it wouldn't even touch the network (some things to do there rpm-ostree side, but definitely still tractable).
> 
> We could definitely do that too but it would take longer to setup the system on first boot for podman machine users.

I mentioned this in the meeting I think, but just to have it here, the delay for this shouldn't be very long if we skip metadata fetching. Trying it out:

```
[root@cosa-devsh ~]# podman -v
podman version 3.4.4
[root@cosa-devsh ~]# time sh -c \
  'rpm-ostree override replace \
    https://kojipkgs.fedoraproject.org//packages/containers-common/1/41.fc35/noarch/containers-common-1-41.fc35.noarch.rpm \
    https://kojipkgs.fedoraproject.org//packages/containernetworking-plugins/1.0.1/4.fc35/x86_64/containernetworking-plugins-1.0.1-4.fc35.x86_64.rpm \
    https://kojipkgs.fedoraproject.org//packages/podman/4.0.0/0.5.rc4.fc35/x86_64/podman-4.0.0-0.5.rc4.fc35.x86_64.rpm \
    https://kojipkgs.fedoraproject.org//packages/podman/4.0.0/0.5.rc4.fc35/x86_64/podman-plugins-4.0.0-0.5.rc4.fc35.x86_64.rpm --cache-only && \
    rpm-ostree ex apply-live --allow-replacement'
Downloading https://kojipkgs.fedoraproject.org//packages/containers-common/1/41.fc35/noarch/containers-common-1-41.fc35.noarch.rpm...done
Downloading https://kojipkgs.fedoraproject.org//packages/containernetworking-plugins/1.0.1/4.fc35/x86_64/containernetworking-plugins-1.0.1-4.fc35.x86_64.rpm...done
Downloading https://kojipkgs.fedoraproject.org//packages/podman/4.0.0/0.5.rc4.fc35/x86_64/podman-4.0.0-0.5.rc4.fc35.x86_64.rpm...done
Downloading https://kojipkgs.fedoraproject.org//packages/podman/4.0.0/0.5.rc4.fc35/x86_64/podman-plugins-4.0.0-0.5.rc4.fc35.x86_64.rpm...done
Checking out tree 5c93c5d... done
Resolving dependencies... done
Applying 4 overrides
Processing packages... done
Running pre scripts... done
Running post scripts... done
Running posttrans scripts... done
Writing rpmdb... done
Writing OSTree commit... done
Staging deployment... done
Upgraded:
  containernetworking-plugins 1.0.1-1.fc35 -> 1.0.1-4.fc35
  containers-common 4:1-32.fc35 -> 4:1-41.fc35
  podman 3:3.4.4-1.fc35 -> 3:4.0.0-0.5.rc4.fc35
  podman-plugins 3:3.4.4-1.fc35 -> 3:4.0.0-0.5.rc4.fc35
Use "rpm-ostree override reset" to undo overrides
Run "systemctl reboot" to start a reboot
NOTICE: Experimental commands are subject to change.
Computing /etc diff to preserve... done
Updating /usr... done
Updating /etc... done
Running systemd-tmpfiles for /run and /var... done
Upgraded:
  containernetworking-plugins 1.0.1-1.fc35 -> 1.0.1-4.fc35
  containers-common 4:1-32.fc35 -> 4:1-41.fc35
  podman 3:3.4.4-1.fc35 -> 3:4.0.0-0.5.rc4.fc35
  podman-plugins 3:3.4.4-1.fc35 -> 3:4.0.0-0.5.rc4.fc35
Successfully updated running filesystem tree; some services may need to be restarted.

real    0m19.822s
user    0m0.390s
sys     0m0.235s
```

(Notice the `--cache-only` switch.)

It looks like v4 needs https://bodhi.fedoraproject.org/updates/FEDORA-2022-d0d128e8f0 which should go into FCOS soon, which is why I had to replace `containers-common` and `containernetworking-plugins` too. Once it's in FCOS, we wouldn't need to, so it'd be a bit faster (but probably not by much).

**Comment by baude** [comment]
> I've tried to make a PoC with both v3 & v4 installed simultaneously in FCOS:
> 
>     * podman4 package: [copr](https://copr.fedorainfracloud.org/coprs/g/CoreOS/podman4/), [src](https://src.fedoraproject.org/fork/siosm/rpms/podman/commits/f35-v4)
> 
>     * FCOS config changes: https://github.com/travier/fedora-coreos-config/commits/podman4
> 
> 
> This gives me a working FCOS system with both v3 (`podman`) and v4 (`podman4`) available, with a default to v3. I tried creating containers with v4 and it works but I'm not sure that it is using the new network stack as I'm not familiar enough with the config change, etc.

v3 and v4 are not compatible with each other because of their network stacks; more over our team has no interest in supporting that use case.

**Comment by baude** [comment]
if you examine who we are competing with here, waiting for fcos to download anything is basically a no-go.  we are trying to deliver a first class user-experience by using fcos and because there is no message feedback from fcos while its vm is booting, people will be left wondering what's going on.

anyways, nothing here that was not said at the meeting on why we want what we asked for -- and we really appreciate the help.

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/JIXXRY4HMZQAHKY6UEXLQ3IB4EUB4X3M/).

```
12:37:34    dustymabe | #agreed It would be nice if we could have podman 3 and 4 co-installable in
                      | F35 so users and podman-machine could use our more stable streams with
                      | podman v4. However, there is definitely some work left to do there. If that
                      | work doesn't get done and if the podman team is happy with their users
                      | being on `next` when the F36 beta lands then that may be the approach that
                      | wins.
```

**Comment by rhatdan** [comment]
Our current plan is to use our own F35 Coreos + podman 4.0 in a separate REPO until F36 CoreOS exists, at which point we will switch over.  The team thinks it is too much work to try to deal with coinstalling the packages.

**Comment by dustymabe** [comment]
Hey @rhatdan - F36 beta will be out mid march at which point `next` will switch over. Not sure what your timeframe is.

**Comment by dustymabe** [comment]
Also worth pointing out that building your own `coreos` stream is a lot of work too. It's definitely easy to `cosa build` and make one, but not easy to continuously update/run the tests, host the bits, manage the update graph and maintain the failures. You essentially become your own OS distributor at that point :)

**Comment by rhatdan** [comment]
No question, we want to get back on the F36 bandwagon as quick as possible, so yes we will switch as soon as we can.

**Comment by dustymabe** [comment]
Closing this out. Our `next` stream (based on Fedora 36) has podman 4.0 and we'll moving over `testing` and `stable` shortly. Nothing else to be done here.

**Comment by oshoval** [comment]
Hi, is there still a way to install podman v4 on f35 ?
the copr that used to work isn't available anymore

Thanks

**Comment by dustymabe** [comment]
@oshoval this is the wrong place to ask that question. Maybe `#podman` in IRC? I will note that F35 is EOL.

Marking these two comments as off topic.
