### ISSUE TITLE
Unused etcd users prevent k0s' installation.

### ISSUE THREAD

**Issue by OrvilleQ** [coreos/fedora-coreos-tracker#1083]
**Describe the bug**
I'm trying to use k0s with Fedora CoreOS and the `k0s install controller` command give me this: 

```Error: failed to create controller users: exit status 9```

`exit 9` for `useradd` means the user already exists. Therefore, I tried to del the user with `usedel` but it said the user does not exist.

So wired things happened here:

```
[root@localhost ~]# useradd etcd
useradd: user 'etcd' already exists
[root@localhost ~]# userdel etcd
userdel: user 'etcd' does not exist
```

I could get autocomplete with the username `etcd` but I can't find it in `/etc/passwd` or `/etc/shadow`, or anywhere. and there are also some unused user aims for certain app, like `cockpit-ws`, `kube`, `ceph`...

I'm wandering where this user came from and why I can't remove it.

Thanks for your help.

**System details**
 - Bare Metal
 - Fedora CoreOS 35.20220103.3.0

**Comment by bgilbert** [comment]
Fedora CoreOS defines system users and most system groups in `/usr/lib/{passwd,group}`, which are read by `nss-altfiles` (see `/etc/nsswitch.conf`).  Any program querying users via NSS should find them; for example, try `id -u etcd`.  However, since they're not in `/etc/{passwd,group}`, `shadow-utils` tools like `userdel` can't affect them.

**Comment by OrvilleQ** [comment]
> Fedora CoreOS defines system users and most system groups in `/usr/lib/{passwd,group}`, which are read by `nss-altfiles` (see `/etc/nsswitch.conf`). Any program querying users via NSS should find them; for example, try `id -u etcd`. However, since they're not in `/etc/{passwd,group}`, `shadow-utils` tools like `userdel` can't affect them.

Thanks for your answer, I do find the `etcd` user under the location you said, but `/usr/lib` is readonly means I can't modify it.

So, is there any good reason we have to pre-define user like `etcd`, `ceph` and `cockpit-ws`?

**Comment by bgilbert** [comment]
Some of those accounts are arguably there for historical reasons.  We can't remove them, though, because that would affect existing machines on upgrade, and some of those machines may be using the accounts.

It sounds like k0s wants the `etcd` user to exist, though.  Can the k0s installer be fixed to use an existing user account if present?

**Comment by OrvilleQ** [comment]
I'm not sure. Is not like wants the user to exist to me, more like the user is under controller by k0s in its lifecycle. Besides, k0s will try to del the user too while it uninstalls the cluster.

I'll open an issue on k0s side too.

**Comment by OrvilleQ** [comment]
So they have made a fix in newer version. Nothing goes wrong now.
