### ISSUE TITLE
Can't boot Fedora Coreos custom iso in uefi mode

### ISSUE THREAD

**Issue by rimvydukas** [coreos/fedora-coreos-tracker#1109]
**Describe the bug**
I wanted to modify some menus in grub.cfg of fedora coreos iso image. So I mounted iso, copied contents to my folder, modified required things and tried to create bootable iso file again. Used the following command:

sudo genisoimage -U -A "fedora-coreos-35.20220131.3.0" -V "fedora-coreos-35.20220131.3.0" -volset "fedora-coreos-35.20220131.3.0" -J -joliet-long -r -v -T -o ~/fcos-modified.iso -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -eltorito-alt-boot -e images/efiboot.img -no-emul-boot .

Problem is that I'm able to boot such iso inly in BIOS mode on Vmware but not in uefi:/ What am I doing wrong? I have no such problems with Redhat Coreos when doing the same steps.

**Expected behavior**
Boot the iso in UEFI mode

**Actual behavior**
Not able to boot the is in UEFI mode

**System details**
 - Fedora CoreOS version 35.20220131.3.0

**Comment by bgilbert** [comment]
We don't support regenerating the ISO image in this way.  Since this isn't a bug, I'll close.  You could try asking in the [coreos tag](https://discussion.fedoraproject.org/tag/coreos) of the Fedora discussion site.

If that procedure works with RHEL CoreOS, it is surprising that it doesn't work with Fedora CoreOS.  If you'd like more details on how the ISO image is assembled, the code is available [here](https://github.com/coreos/coreos-assembler/blob/main/src/cmd-buildextend-live).

**Comment by dustymabe** [comment]
One other thing.. Depending on the customizations you are making to the GRUB config you might be able to achieve the same goal with `coreos-installer iso customize`. See the [docs](https://coreos.github.io/coreos-installer/customizing-install/).
