### ISSUE TITLE
Update hardware version in VMware OVA after 6.5/6.7 EOL date

### ISSUE THREAD

**Issue by miabbott** [coreos/fedora-coreos-tracker#1141]
(Split off of https://github.com/coreos/fedora-coreos-tracker/issues/1119; please see that issue for relevant discussion)

VMware vSphere 6.5/6.7 is scheduled to be EOL on Oct 15, 2022.  This provides an opportunity to change the hardware version that we use by default to something newer, which would effectively block users on those older versions of vSphere from booting FCOS as a guest VM.

We should evaluate changing the hardware version to something newer than 13 (the current default) after the EOL date of vSphere 6.5/6.7

A reasonable new version would be ~16~ 17; see the KB article for more details about hw versions - https://kb.vmware.com/s/article/1003746

**Comment by bgilbert** [comment]
All of the VMware products requiring version 16 are already EOL, so we should move to 17 instead.

**Comment by miabbott** [comment]
> All of the VMware products requiring version 16 are already EOL, so we should move to 17 instead.

Ah indeed, makes sense then!

**Comment by travier** [comment]
We're past the EOL date for ESXi 6.5 and 6.7. We can revisit this ticket.

**Comment by bgilbert** [comment]
We've [already announced this change](https://lists.fedoraproject.org/archives/list/coreos-status@lists.fedoraproject.org/message/OC2FRKNF6LGHJG5G5G2XYHZ6VKCDPEVW/) to coreos-status.

**Comment by bgilbert** [comment]
Fix in https://github.com/coreos/fedora-coreos-config/pull/2019.

**Comment by travier** [comment]
I don't think we need to meet again indeed. Maybe we should sent an update / reminder to the status list?

**Comment by Okeanos** [comment]
Will you track somewhere what the last FCOS OVA version with hardware level 13 is? Would it be possible to offer a "legacy, unsupported"-annotated link to such a version?

Would it make sense to tell people on the [download page](https://getfedora.org/en/coreos/download?tab=metal_virtualized&stream=stable&arch=x86_64) or add an attribute in the streams json that describes the current (supported) hardware level?

I understand that phasing the old level out is a very good idea (in particular because VMware doesn't support them anymore anyway) but I would welcome a good user experience surrounding that change. In particular being able to pick a "legacy" OVA for a (short) while would potentially make things a little more comfortable. If that isn't possible/feasible I'd still wish for clear communication on the downloads page explaining the minimum requirements.

**Comment by dustymabe** [comment]
Hey @Okeanos. We can note here in this ticket what the last versions were and we will (should)  update [this docs page](https://docs.fedoraproject.org/en-US/fedora-coreos/platforms/) noting the minimum version. 

We have [docs](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-vmware/#_modifying_ovf_metadata) for how to modify the VMWare artifact if someone absolutely needs to go back.

**Comment by Okeanos** [comment]
That's fair enough and I concede that this shouldn't be happening. I was mainly interested in knowing the exact cut-off and potentially being able to look it up easily (for an arbitrary value of easy). The information you provided just now as well as the plans for rollback instructions are enough to satisfy my curiosity. Thanks :)

**Comment by bgilbert** [comment]
[coreos-status post](https://lists.fedoraproject.org/archives/list/coreos-status@lists.fedoraproject.org/message/6VGX6OU6AS4VGTVCGFFACM43Y5RMGWY7/).

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `37.20221021.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `36.20221030.2.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `36.20221030.3.0`.
