### ISSUE TITLE
F36: No network on rpi4

### ISSUE THREAD

**Issue by perosb** [coreos/fedora-coreos-tracker#1145]
**Describe the bug**
Switching to F36 results in no network on rpi4.
I'll close this once I can confirm network works again.

I'm hoping this is the same as https://bugzilla.redhat.com/show_bug.cgi?id=2053729 which should be resolved in future kernel upgrade.
```
Peter Robinson 2022-03-27 10:01:48 UTC
So the final fix for this has landed upstream in the 5.18 merge window, it's tagged as a fix so should hopefully land in 5.17.x RSN

commit 8d3ea3d402db94b61075617e71b67459a714a502
Author: Jeremy Linton <[jeremy.linton@arm.com](mailto:jeremy.linton@arm.com)>
Date:   Wed Mar 9 22:53:58 2022 -0600

    net: bcmgenet: Use stronger register read/writes to assure ordering
    
    GCC12 appears to be much smarter about its dependency tracking and is
    aware that the relaxed variants are just normal loads and stores and
    this is causing problems like:
```

I'll try to confirm the same when I get some time.

**System details**
 - Raspberry Pi 4
 - 36.20220325.1.0

**Comment by dustymabe** [comment]
Thanks @perosb for reporting the issue and linking to the BZ. According to the BZ it's fixed in [8d3ea3d](
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit?id=8d3ea3d402db94b61075617e71b67459a714a502). If I look at the kernel in the [latest `rawhide`](https://builds.coreos.fedoraproject.org/browser?stream=rawhide&arch=aarch64) (`kernel-5.18.0-0.rc0.20220325git34af78c4e616.7.fc37`) it should include that fix. If you want to test that out feel free. Either way we'll keep track of it.

**Comment by dustymabe** [comment]
According to https://bugzilla.redhat.com/show_bug.cgi?id=2053729 this is fixed with `kernel-5.17.2-300.fc36`. That or newer kernel with make it into the next `next` release.

**Comment by perosb** [comment]
confirmed that network works on `36.20220418.1.0`

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `36.20220418.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
Luckily this issue never hit the `testing` or `stable` streams.
