### ISSUE TITLE
F36 Getting libbpf errors

### ISSUE THREAD

**Issue by Nemric** [coreos/fedora-coreos-tracker#1164]
**Describe the bug**

That's not really a bug, and I can't see side effect :/ but I have these logs : (from bottom to top)
```
Failed to load BPF object: Operation not permitted
libbpf: failed to load BPF skeleton 'restrict_ifaces_bpf': -1
libbpf: failed to load object 'restrict_ifaces_bpf'
libbpf: Error in bpf_object__probe_loading():Operation not permitted(1). Couldn't load trivial BPF program. Make sure your kernel supports BPF (CONFIG_BPF_SYSCALL=y) and/or that RLIMIT_MEMLOCK is set to big enough value.
libbpf: failed to load BPF skeleton 'socket_bind_bpf': -1
libbpf: failed to load object 'socket_bind_bpf'
libbpf: Error in bpf_object__probe_loading():Operation not permitted(1). Couldn't load trivial BPF program. Make sure your kernel supports BPF (CONFIG_BPF_SYSCALL=y) and/or that RLIMIT_MEMLOCK is set to big enough value.
pam_unix(systemd-user:session): session opened for user core(uid=1000) by (uid=0)
```

**Reproduction steps**
Each time I login to the server, via ssh, I only have core account and ssh access

**Expected behavior**
no errors

**System details**
 - Bare Metal
 - Fedora CoreOS 36.20220325.1.0 installed from PXE

```
[core@Curie ~]$ ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) unlimited
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 14937
max locked memory           (kbytes, -l) 8192
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1024
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 14937
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

**Ignition config**
Here are the ignitions files used to provision the machine, the first one that merge the others is curie.ign, I proudly use the fabulous merging feature to reuse configs, see **Additional information** below
[ignitions.zip](https://github.com/coreos/fedora-coreos-tracker/files/8474629/ignitions.zip)

**Additional information**
All services that are used on this server are also used in other servers, except that the docker registry is used here to act as a proxy registry, other servers use Fedora CoreOS 35.20220313.3.1 with the same "ign merge" dependencies and more
- First uses PXE live boot (diskless use)
- Second uses classical baremetal install with auto updates

These 2 machines don't log any libbpf errors

**Comment by Nemric** [comment]
**Additional information**
Oh ! and I use a cached nfs share with fscache/cachefilesd (for the configs of containerized services) 
fscache has been rewritten, and comme in kernel 5.17, so it's quite new

**Comment by Nemric** [comment]
Same behaviour with 36.20220410.1.1, after update and after new install

**Comment by Nemric** [comment]
Well, am I the only one ? All my machine are now on, at least, 36.20220505.3.2 and one on Next release 36.20220522.1.0 this log line appear in all of them as soon as I log in : 
`libbpf: Error in bpf_object__probe_loading():Operation not permitted(1). Couldn't load trivial BPF program. Make sure your kernel supports BPF (CONFIG_BPF_SYSCALL=y) and/or that RLIMIT_MEMLOCK is set to big enough value.`

**Comment by ed-flanagan** [comment]
I've encountered this message before too (not just on Fedora, however).
For `bpftool v6.8.0` I get an additional message: `libbpf: Failed to bump RLIMIT_MEMLOCK (err = -1), you might need to do it explicitly!` (comes from https://github.com/torvalds/linux/blob/7e062cda7d90543ac8c7700fc7c5527d0c0f22ad/tools/lib/bpf/libbpf.c#L4428 afaict).
Feel that implies it's likely specifically the memlock, not the syscall support.

Most recently, I was using a Mac x86 host for a VBox guest running Fedora 36, updated with kernel `5.18.9-250.vanilla`.
Confirmed a number of `CONFIG_BPF_*` values are `y` in `/boot/config-5.18...` including `SYSCALL` and `STREAM`.

I tried a couple things
1. Setting `memlock` to `unlimited` in `/etc/security/limits.conf` (or `/etc/security/limits.d/$USER.conf`). E.g.
    ```
    *               soft    memlock             unlimited
    *               hard    memlock             unlimited
    ```
    * https://github.com/RPCS3/rpcs3/issues/9328
    * https://access.redhat.com/solutions/61334
    * https://wiki.archlinux.org/title/PipeWire#Increasing_RLIMIT_MEMLOCK
    * Checked live values with `prlimit` and `ulimit -a`
2. Running `bpftool` with `sudo`

Running with `sudo` worked for me (even without the limits adjustment). 
Leads me to believe it's something to do with running `bpftool` as a non-root user. Unfortunately, I have no clue what it would be doing (permissions or otherwise). BPF might doing something where the system settings don't matter(?).

Cilium's eBPF examples unlock in-program, e.g. https://github.com/cilium/ebpf/blob/eb74eecf3f5cd537c49e5eb326d80b59f4e885d0/examples/ringbuffer/main.go#L33-L35
Was introduced in https://github.com/cilium/ebpf/pull/438

There's also https://lore.kernel.org/bpf/59860cf4-2113-9e8a-3edb-1b7a19dff2c6@iogearbox.net/T/ which says 

> The need to increase RLIMIT_MEMLOCK to do anything useful with BPF is
one of the first extremely frustrating gotchas that all new BPF users go
through and in some cases have to learn it a very hard way.
> 
> Luckily, starting with upstream Linux kernel version 5.11, BPF subsystem
dropped the dependency on memlock and uses memcg-based memory accounting
instead. Unfortunately, detecting memcg-based BPF memory accounting is
far from trivial (as can be evidenced by this patch), so in practice
most BPF applications still do unconditional RLIMIT_MEMLOCK increase.

Looks like there's a whole series of these changes
https://patchwork.kernel.org/project/linux-kselftest/list/?series=629163

Poking around history, I don't think https://github.com/torvalds/linux/commit/a777e18f1bcd32528ff5dfd10a6629b655b05eb8 is in 5.18. Don't know if that fixes anything.

All this to say, does look like it's a `bpftool` behavior thing, might be "fixed" (improved experience) in the future. But looks like a thorn in general (still don't actually know why `sudo` fixes things for me).

**Comment by Nemric** [comment]
Looks like it has been auto resolved ;)

**Comment by dustymabe** [comment]
Nice. Thanks for following up!
