### ISSUE TITLE
Work around coreos-koji-tagger delays

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1185]
We have lockfiles that define RPM versions of packages that go into Fedora CoreOS. These lockfiles are bumped either by the [lockfile bumper](https://github.com/coreos/fedora-coreos-pipeline/blob/main/jobs/bump-lockfile.Jenkinsfile) or by a PR to the configs repo for an override. Once the files are updated in git the [coreos-koji-tagger](https://github.com/coreos/fedora-coreos-releng-automation/tree/main/coreos-koji-tagger) then identifies any builds that aren't in the `coreos-pool` koji tag and tags them over. Once they are tagged a new yum repo is made and only then can they be consumed.

Baked into this process is a delay between when the files are updated in git and when the RPMs are available in the yum repo, which means builds kicked off in that time will fail because it can't find all the RPMs that are needed. We need to handle this delay gracefully for our pipeline builds and for our CI runs at a minimum. Up until this point we've just been kicking off a new run if one fails for this reason, but I think it's time we come up with a way to not have this problem.

**Comment by jlebon** [comment]
One avenue to investigate for this is to leverage fedmsgs since coreos-koji-tagger already listens on it. For override PRs, there's [github2fedmsg](https://apps.fedoraproject.org/github2fedmsg) that might be able to trigger a fedmsg when e.g. the PR is approved or a label gets added. The tagger can comment back when the packages were tagged. For lockfile bumps, we can use do a fedmsg "RPC" like we do for signing to get the packages tagged before we push.

**Comment by c4rt0** [comment]
Absolutely, thanks Jonathan!

**Comment by jlebon** [comment]
We had a meeting about this. We agreed that ideally the pool repo would be updated before the lockfiles are committed to the final branches. One idea there was to have a GitHub Action that triggers on a label on the override PR to sync the lockfiles to some secondary branch that the tagger learns to look at.

A more tactical fix is to implement something similar to what we already implement in CoreOS CI on the f-c-c repo: https://github.com/coreos/fedora-coreos-config/blob/a85766ed7a315e3c09629dbf11cc5bdf02560cfc/.cci.jenkinsfile#L15-L16

We manually download the overrides into the `overrides/rpm` directory and then do `cosa fetch --with-cosa-overrides`. We can do the same thing in the pipeline, but scope it down to only do this on non-production streams and only if the overrides files were changed recently (initial suggestion is 2h). We don't want to do this on production streams because we expect all packages to be in the pool and signed. And we don't want to do this if the overrides files didn't change recently to not hide larger tagging issues.

The new logic would be inserted [in the fetch stage](https://github.com/coreos/fedora-coreos-pipeline/blob/a1b1f8d421c180111fdba8ed2d0bcf684ea1c490/jobs/build.Jenkinsfile#L232-L236) before `cosa fetch`.

Probably easier to move `download-overrides.py` to cosa so we don't have to fetch it from the automation repo.

**Comment by jlebon** [comment]
Ideally we'd fix this for CoreOS CI builds in other repos too. Short-term, we could add that logic also to [cosaBuild](https://github.com/coreos/coreos-ci-lib/blob/main/vars/cosaBuild.groovy). We could look at having the pipeline use that too, though I'm concerned because of the amount of customizations we do, it'd hide the logic and make it harder to follow.

Probably argues then for having that "git check" logic directly live in `download-overrides.py`, e.g. as a `--skip-overrides-older-than 2h` switch to minimize duplication.

**Comment by c4rt0** [comment]
We now have the [PR with a workaround](https://github.com/coreos/fedora-coreos-pipeline/pull/863) merged into jobs/[build.Jenkinsfile](https://github.com/coreos/fedora-coreos-pipeline/blob/main/jobs/build.Jenkinsfile). 

> Ideally we'd fix this for CoreOS CI builds in other repos too. Short-term, we could add that logic also to [cosaBuild](https://github.com/coreos/coreos-ci-lib/blob/main/vars/cosaBuild.groovy). We could look at having the pipeline use that too, though I'm concerned because of the amount of customizations we do, it'd hide the logic and make it harder to follow.
> 
> Probably argues then for having that "git check" logic directly live in `download-overrides.py`, e.g. as a `--skip-overrides-older-than 2h` switch to minimize duplication.
> 

I am wondering what's next? 
[download-overrides.py](https://github.com/coreos/coreos-assembler/blob/main/src/download-overrides.py) which is now being called by the implemented workaround has now been moved to [coreos-assembler/src](https://github.com/coreos/coreos-assembler/tree/main/src). 
By default, the 2h ([120 minutes](https://github.com/coreos/fedora-coreos-pipeline/blob/main/jobs/build.Jenkinsfile#L131)) window is for now hard-coded into the solution. 
I feel like I should work on `--skip-overrides-older-than 2h` and implement it in the [parameters](https://github.com/coreos/fedora-coreos-pipeline/blob/main/jobs/build.Jenkinsfile#L16) section...

**Comment by c4rt0** [comment]
Closing this issue for now. Will re-open if further changes will be required.
