### ISSUE TITLE
New Package Request: not packaged yet

### ISSUE THREAD

**Issue by jtoppins** [coreos/fedora-coreos-tracker#1269]
Please try to answer the following questions about the package you are requesting:

1. What, if any, are the additional dependencies on the package? (i.e. does it pull in Python, Perl, etc)

depends on solution implementation; if nft based requires nftables userspace tools, if eBPF based requires at minimum a glibc runtime and libbpf.

3. What is the size of the package and its dependencies?

not packaged so cannot say

4. What problem are you trying to solve with this package? Or what functionality does the package provide?

Provide filters that can be applied to a kernel bond interface (or its slaves) that provide the same functionality as [OVS slb-bonding](https://docs.openvswitch.org/en/latest/topics/bonding/).

5. Can the software provided by the package be run from a container?  Explain why or why not.

It doesn't really make sense as this is connecting the host to the network, thus the bond device would be connected to the bridge device whos veths would be connected to various containers/VMs.

```
ASCII Art:

            ----------
   cont1----+  BR0   +---- Bond1 --- rest of network
   cont2----+        |
            ----------
```

6. Can the tool(s) provided by the package be helpful in debugging container runtime issues?

haha no; the tools, bpftool or nft, can be used to debug the filters that are applied.

7. Can the tool(s) provided by the package be helpful in debugging networking issues?

yes, see above.

8. Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.

I don't know, I don't do coreOS.

9. In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?

What do you mean?

10. Can the tool(s) provided by the package be used to do things we’d rather users not be able to do in FCOS? (e.g. can it be abused as a Turing complete interpreter?)

No idea, the kernel already support the bpf system call so in theory a user can already load BPF programs and execute arbitrary code given they have the correct permissions.

11. Does the software provided by the package have a history of CVEs?

This is bpf or nft based, I don't know their histories.

**Comment by bgilbert** [comment]
Thanks for the feature request.  It sounds as though this is a request for general functionality in Fedora CoreOS, and isn't about adding a specific existing package.  As such, our new-package checklist isn't really a good fit, since we'll want to have a broader discussion about what a solution might look like.  (And that solution might not involve a package at all.)  Therefore, I'll close this.  Please [open an enhancement request](https://github.com/coreos/fedora-coreos-tracker/issues/new?assignees=&labels=kind%2Fenhancement&template=enhancement.md) instead, with as much detail as possible about the needed functionality so we can properly evaluate it.
