### ISSUE TITLE
New Package Version Request: open-vm-tools

### ISSUE THREAD

**Issue by fifofonix** [coreos/fedora-coreos-tracker#1286]
open-vm-tools is already available via package layering.

There is a newly discovered security vulnerability with the package and a new release (12.1.0) addressing this.

This issue is just to flag that this new version is eagerly anticipated - and hopefully can be accommodated in upcoming releases.

If there is a recommended means for patching layered systems ahead of a formal CoreOS stream release I'd be interested in understanding that - I know that it is possible to add an additional rpm source and rpm-ostree can install based on an additional source.  Also, I am aware that it is also possible to run open-vm-tools as a privileged container.  Perhaps these kind of situations are precisely one of the benefits of containerizing additional software rather than layering?

**Comment by dustymabe** [comment]
Hey @fifofonix - since `open-vm-tools` isn't in the base OSTree for FCOS there's not much we can do here. The appropriate place to follow progress is in the BZs for the package (can find the link from https://packages.fedoraproject.org/pkgs/open-vm-tools/open-vm-tools/)

In this case the bug you want to follow is [Bug 2120976](https://bugzilla.redhat.com/show_bug.cgi?id=2120976). Status updates will be posted there when new builds are available.
