### ISSUE TITLE
alias `quay.io/fedora/fedora-coreos:stable` to `:latest` in quay

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#1309]
If you go to https://quay.io/repository/fedora/fedora-coreos quay says: `podman pull quay.io/fedora/fedora-coreos` but that doesn't work because the runtime assumes `:latest`.

(This is definitely a quay bug)

But that said, it would seem to make sense for us to point `:latest` at `:stable`, right?

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/N5AFMFABL2MIOV6VQUUBZ6YPR27CD55R/).

```
13:12:32  dustymabe | #agreed While this would provide benefit to new users who just want to pull FCOS
                    | and see what's inside we could see some potential problems with it and would like
                    | to defer implementing something like this until our update story for CoreOS
                    | Layering (https://github.com/coreos/fedora-coreos-tracker/issues/1263) is figured out.

```

To summarize the conversation a bit more:

Obviously being able to just pull `quay.io/fedora/fedora-coreos` (which will pull the `:latest` tag by default) is attractive because users will get `$something` on their first try.

There are potential problems with this though:

- Forcing users to know about streams and what stream they are on could be a nice forcing function to them being more educated about what our streams are and why they are useful.
- If a user tries to rebase using `rpm-ostree rebase --experimental ostree-unverified-registry:quay.io/fedora/fedora-coreos` what actually shows up in `rpm-ostree status` output and what is the user actually following?
    - We could make some logical assumptions here and fixup the tag client side in `rpm-ostree` code, but that requires assumptions and could be (probably is) FCOS specific.
    - If registries properly supported `redirects` then we could redirect `quay.io/fedora/fedora-coreos:latest` to `quay.io/fedora/fedora-coreos:stable` and there would be much less concern here because the client tooling would get and reflect `:stable`.
- This may have impact (unkown at this point) on our yet to be worked out [implementation of zincati updates for OSTree Native Containers](https://github.com/coreos/fedora-coreos-tracker/issues/1263).

So while we work out some details we're electing to defer decisions on implementing this to a later point in time.

**Comment by cgwalters** [comment]
In the interest of keeping our issue list small, I'm going to close this for now.
