### ISSUE TITLE
Move Ignition glue to a package

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#1311]
There's some possibility that Fedora IoT will use Ignition; this would make it easier for people to try pre-built images, and it may be used in some production paths too.

They want to share code with us, but today their build process can only accept RPMs as input, realistically.  So...this issue is to track agreement and implementation of moving our dracut modules into a package (ignition subpackage?).

We had a lot of churn on this originally, and honestly I love not having to think about packages for this stuff - feels like a breath of fresh air to submit a PR, have it pass CI and merge and not touch a spec file at all or any manual build tools and it just ships.  But...yeah, RPM :cry: 

So, any thoughts/objections to this?

This also helps start the ball rolling on some other things, for example...they already use coreos-installer, and suddenly its ability to inject Ignition is useful.  And further, we could try to factor out the infrastructure we have for `cosa run` and for that matter, I think `kola` could even work too.  So we could try to share a lot more stuff potentially after this.

**Comment by miabbott** [comment]
Tangentially related - https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/OPSZ7I4JLFTDC65FPEOUN4CZJNEGKGDS/

**Comment by bgilbert** [comment]
In the long run, I think we should try to move the glue upstream into the Ignition repo (maybe into the Ignition binary) and have some sort of customization mechanism on top.  For example, the transposefs infrastructure is generally useful but the knowledge of what partitions to copy is distro-specific.

But that's a larger change.  For now, I think generalizing the existing code to support another distro is a reasonable intermediate step, and no doubt we'd learn something from it.

One option is to package the Dracut modules directly from fedora-coreos-config.  @cgwalters, are you imagining that the actual code would move?

**Comment by cgwalters** [comment]
> One option is to package the Dracut modules directly from fedora-coreos-config. @cgwalters, are you imagining that the actual code would move?

I don't have a strong opinion.  I'd be fine keeping it in the config git repo for now.  But if we commit to this path it does seem to make more sense to move into a separate repo, because if we don't, it will be cloned by coreos-assembler but not used.

**Comment by dustymabe** [comment]
> if we don't, it will be cloned by coreos-assembler but not used.

This implies we also consume the RPM, which I think was an open question.

**Comment by dustymabe** [comment]
We discussed this at the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/NC6KL5OOIYOEVHYECS2A4TDWKYDQMORN/).

```
13:12:46    bgilbert | #agreed We'll work with the IoT team to help create an RPM
                     | (sub)package for the Ignition fedora-coroes-config glue
                     | needed by IoT.  Initially we'll package the files directly
                     | from f-c-c, and CoreOS itself will not ship the package.
                     | If adjustments are needed to the glue, we'll make them
                     | upstream in f-c-c.  After we gain some experience, we'll
                     | re-evaluate where the code should live and what sort of
                     | refactoring should be done.
```

**Comment by runcom** [comment]
thanks for this folks! what we're really doing nowadays just requires in dracut https://github.com/runcom/osbuild/blob/48404772ada5a44d3ea7b6f33cf0faa606588e13/stages/org.osbuild.ignition.setup-user 

but also, we would love to understand where to ship something like the firstboot complete service too https://github.com/runcom/osbuild/blob/581703518e7e1ced16d69f91a83a7ca78aa081ec/stages/org.osbuild.ignition.firstboot-complete

the other glue, setting kargs for ignition and the like already live in osbuild-composer

**Comment by runcom** [comment]
So far, what we've been able to came up with for a working Ignition+ostree system is, apart from installing `ignition`:

- [ignition-firstboot-complete.service](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/05core/usr/lib/systemd/system/coreos-ignition-firstboot-complete.service)
- [ignition-setup-user.service](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/05core/usr/lib/dracut/modules.d/35coreos-ignition/coreos-ignition-setup-user.service) (dracut)
- [ignition-ostree-mount-var.service](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/ignition-ostree-mount-var.service) (dracut)

I'm sure I'm missing some else which is critical perhaps so I'd love to know if there's any other critical service we would need. The above is the bare minimum needed to have ignition run and write just files/directories, setup user/keys/pwds and enable/disable systemd services, which is what [we're after](https://github.com/coreos/butane/issues/396) as a first iteration.

As @bgilbert pointed out in the community meeting, we'd love to subpackage the ignition RPM with something like `ignition-enable` or `ignition-edge` or `ignition-glue` as a first pass - does anybody have any opinion?

**Comment by bgilbert** [comment]
That list looks good as a basic set of services.  Some other things to consider:

- **Required**: if you're using the upstream Ignition firstboot logic, `/boot/ignition.firstboot` will need to exist in shipped images, and you'll need to [have GRUB add](https://github.com/coreos/coreos-assembler/blob/9e68cf216b6c34acbe48966da8ad3902f18f1819/src/grub.cfg#L75-L86) `ignition.firstboot` to the kernel arguments if that file exists.  (You can ignore the `source` and `ignition_network_kcmdline` parts of that config section.)  Also, you'll need to add `ignition.platform.id=<platform>` to your kernel arguments (presumably `metal` for Edge).
- **Strongly recommended**: a mechanism to conditionally start networking in the initramfs if `ignition-fetch-offline.service` creates `/run/ignition/neednet`, similar to [coreos-enable-network.service](https://github.com/coreos/fedora-coreos-config/blob/f907422f874d254a2370359da89db3ba9fb7ceb8/overlay.d/05core/usr/lib/dracut/modules.d/35coreos-network/coreos-enable-network.service).  Without this, Ignition won't be able to fetch from remote URLs, or (if you unconditionally enable networking) the network may be started unnecessarily.
- **Strongly recommended**: install the `ssh-key-dir` package.  With Ignition's recommended compile-time settings (which are used in the RHEL 9 package) it will write SSH keys to `~username/.ssh/authorized_keys.d/ignition`.  ssh-key-dir is needed for sshd to read keys from the `authorized_keys.d` directory.  Ignition can be told to write directly to `~/.ssh/authorized_keys` via a compile-time option, but that's not recommended, because then `authorized_keys` can become a mishmash of keys added by different sources/tools.
- **Recommended**: if you'll have any default users on the system (such as FCOS's `core`), consider how they will be created.  Creating them with systemd-sysusers introduces a bug where adding SSH keys with Ignition causes that user to lose any default groups, because systemd-sysusers won't create the user if Ignition already did.  We addressed this by creating the `core` user from an [Ignition base config](https://github.com/coreos/fedora-coreos-config/blob/f907422f874d254a2370359da89db3ba9fb7ceb8/overlay.d/05core/usr/lib/dracut/modules.d/40ignition-conf/00-core.ign) instead.  You could also ship the user baked into the image.
- **Quality of life**: if machines might have multiple system consoles configured, consider enabling [99journal-conf](https://github.com/coreos/fedora-coreos-config/tree/f907422f874d254a2370359da89db3ba9fb7ceb8/overlay.d/05core/usr/lib/dracut/modules.d/99journal-conf) and [10coreos-sysctl](https://github.com/coreos/fedora-coreos-config/tree/f907422f874d254a2370359da89db3ba9fb7ceb8/overlay.d/05core/usr/lib/dracut/modules.d/10coreos-sysctl) to ensure that secondary consoles also get Ignition log messages.
- **Quality of life**: if you want CoreOS-style Ignition status information at the login prompt, enable [coreos-ignition-write-issues.service](https://github.com/coreos/fedora-coreos-config/blob/f907422f874d254a2370359da89db3ba9fb7ceb8/overlay.d/05core/usr/lib/systemd/system/coreos-ignition-write-issues.service) and possibly [coreos-check-ssh-keys.service](https://github.com/coreos/fedora-coreos-config/blob/f907422f874d254a2370359da89db3ba9fb7ceb8/overlay.d/15fcos/usr/lib/systemd/system/coreos-check-ssh-keys.service).
- **Quality of life**: if you'd like error summary information to be printed when Ignition fails, consider enabling [emergency-shell.sh](https://github.com/coreos/fedora-coreos-config/blob/f907422f874d254a2370359da89db3ba9fb7ceb8/overlay.d/05core/usr/lib/dracut/modules.d/99emergency-shell-setup/emergency-shell.sh).

Re package naming, something like `ignition-edge` seems good, because it doesn't imply that the package is trying to support all RHEL builds.  I'm okay with shipping the glue as an Ignition subpackage, but it might be better to ship an entirely separate package for faster iteration.  (We have three separate Ignition specfiles - Fedora, RHAOS 8, and RHEL 9 - that we try to keep in sync.)

**Comment by runcom** [comment]
> * **Strongly recommended**: install the `ssh-key-dir` package.  With Ignition's recommended compile-time settings (which are used in the RHEL 9 package) it will write SSH keys to `~username/.ssh/authorized_keys.d/ignition`.  ssh-key-dir is needed for sshd to read keys from the `authorized_keys.d` directory.  Ignition can be told to write directly to `~/.ssh/authorized_keys` via a compile-time option, but that's not recommended, because then `authorized_keys` can become a mishmash of keys added by different sources/tools.

according to my testing on rhel 9.2 this doesn't seem to be the case tho - meaning, when ignition runs it still writes under .ssh/authorized_keys (and not a directory) - also I can't find from the cs9 spec how ssh-key-dir is pulled in and/or used at all - any more input folks? :thinking:

**Comment by bgilbert** [comment]
Hmm, that's weird, and is worth tracking down.  Ignition `2.14.0-2.el9*` and above should have the [patch](https://gitlab.com/redhat/centos-stream/rpms/ignition/-/commit/d5e3307e9b946f7f8c78585abf4fd9c50743c278) to write to `authorized_keys.d` on RHEL 9.

The `ssh-key-dir` package includes an `/etc/ssh/sshd_config.d` fragment that automatically enables it, so installing the package should be sufficient.  We should probably make it an explicit dependency of the Ignition package though.

**Comment by runcom** [comment]
I can't find ssh-key-dir in rhel either (in brew)

**Comment by runcom** [comment]
to track progress, this is already working fine for our use cases https://github.com/fedora-iot/ignition-edge

**Comment by runcom** [comment]
> Hmm, that's weird, and is worth tracking down. Ignition `2.14.0-2.el9*` and above should have the [patch](https://gitlab.com/redhat/centos-stream/rpms/ignition/-/commit/d5e3307e9b946f7f8c78585abf4fd9c50743c278) to write to `authorized_keys.d` on RHEL 9.

ok, so that revision didn't yet make into nightlies afaict and that's why I'm not getting it - meanwhile, I've added the `ssh-key-dir` package to the system

**Comment by runcom** [comment]
> That list looks good as a basic set of services. Some other things to consider:

https://github.com/fedora-iot/ignition-edge now contains basically all the suggestions and it's been tested and working with r4e :)

**Comment by cgwalters** [comment]
One thing that came up in chat that's strongly related to this is that AIUI today, Edge doesn't have a full Live ISO model like we do with CoreOS.  And it probably would make sense, right?  So alongside packaging Ignition, I guess we we could try to move https://github.com/coreos/fedora-coreos-config/tree/testing-devel/overlay.d/05core/usr/lib/dracut/modules.d/35coreos-live to a package too.

**Comment by runcom** [comment]
> [b.com/coreos/fedora-coreos-config/tree/testing-devel/overlay.d/05core/usr/lib/dracut/modules.d/35coreos-live](https://github.com/coreos/fedora-coreos-config/tree/testing-devel/overlay.d/05core/usr/lib/dracut/modules.d/35coreos-live) to a package too.

we've been seeing ppl asking for a live image for a while now :) that'd be great indeed (although I'd love to keep the current scope of "this is the base ignition-glue" as tiny as possible and then jump on "support a live ISO")

**Comment by miabbott** [comment]
Packaging changes for C9S/RHEL9 - https://gitlab.com/redhat/centos-stream/rpms/ignition/-/merge_requests/13

**Comment by travier** [comment]
The next steps for this issue are tracked in https://github.com/coreos/fedora-coreos-tracker/issues/1582
