### ISSUE TITLE
ppc64le: RHCOS VM fails to boot on IBM Power

### ISSUE THREAD

**Issue by HuijingHei** [coreos/fedora-coreos-tracker#1360]
We currently build RHCOS image using [coreos-assembler](https://github.com/coreos/coreos-assembler), which includes everything needed to build and test the OS comes encapsulated in one container, and the base image is now latest `fedora:36`. Specially, when build image in container, need to call `grub2-install` to install the bootloader for the image, which is now from `grub2-tools-2.06-54.fc36`(in coreos-assembler container).

@mkumatag found that if building from fedora:36's grub package without these 2 patches, rhcos image works.
- https://src.fedoraproject.org/rpms/grub2/blob/f36/f/0215-powerpc-do-CAS-in-a-more-compatible-way.patch
- https://src.fedoraproject.org/rpms/grub2/blob/f36/f/0279-ieee1275-implement-vec5-for-cas-negotiation.patch

We need to pin `grub` in coreos-assembler container to an old version that excluding these 2 patches for ppc64le, and remove the pin if the bug is fixed.

For the detail info see https://issues.redhat.com/browse/OCPBUGS-2152

**Comment by dustymabe** [comment]
The bug itself is locked (private view), but here are the Bodhi updates with the fixes for the problem:

- [`grub2-2.06-58.fc36`](https://bodhi.fedoraproject.org/updates/FEDORA-2022-939b6a00b6)
- [`grub2-2.06-70.fc37`](https://bodhi.fedoraproject.org/updates/FEDORA-2022-0942baead9)
- [`grub2-2.06-70.fc38`](https://bodhi.fedoraproject.org/updates/FEDORA-2022-41fbd19412)

Right now `testing-devel` and `next-devel` do have an even newer version of grub `grub2-2.06-72.fc37` on `ppc64le` but that's only because of a mistake we made [pinning to an older version of grub for another issue](https://github.com/coreos/fedora-coreos-tracker/issues/1352#issuecomment-1370372044). However, that did give @HuijingHei an opportunity to test out a ppc64le `testing-devel` build of `fedora-coreos-37.20221219.20.0-powervs.ppc64le.ova.gz` build and confirm the newer grub does fix the problem.

**Comment by dustymabe** [comment]
Sine we are [dropping our grub2 pin](https://github.com/coreos/fedora-coreos-config/pull/2153) because our [other issue got fixed](https://github.com/coreos/fedora-coreos-tracker/issues/1352#issuecomment-1371225262) we'll continue to use the latest version of grub2 in ppc64le that has the fix for this issue as well.

This means we can close this out. Since `ppc64le` isn't shipped on any production channels I won't make any updates about what release this was fixed in.

It would be really nice if we could start testing on PowerVS as part of our CI but that's probably a separate work item from this.
