### ISSUE TITLE
Create a new GCP udev rules test

### ISSUE THREAD

**Issue by ravanelli** [coreos/fedora-coreos-tracker#1457]
### Describe the enhancement

After we got https://github.com/coreos/fedora-coreos-config/pull/2336 merged, we now need some tests to validate if the rules are ok when working with disks. It should  only run in GCP.

### System details

GCP

**Comment by travier** [comment]
Would be good to land with https://github.com/coreos/fedora-coreos-config/pull/2350 so that the test directly validates the change in the PR.

**Comment by travier** [comment]
A first step would be to create a test that verifies that the files exists in the image and the initrd.

Then we could create a new GCP specific test to verify that those rules work in the Platform.

**Comment by ravanelli** [comment]
@travier I saw we already have something in kola for it, so I added it in this PR https://github.com/coreos/fedora-coreos-config/pull/2385

**Comment by HuijingHei** [comment]
To add kola tests for gcp, need to create confidential vm which needs to pass `--confidential-compute --maintenance-policy=terminate` to gcloud, should I add related option to kola (like [gcp-machinetype](https://github.com/coreos/coreos-assembler/blob/f78ee0e1808c369a1d8e99871c643d1c107a73d6/mantle/cmd/kola/options.go#L120))?

**Comment by HuijingHei** [comment]
> it'd be good to sanity-check that this rule is also functioning correctly by bringing up an instance with a local SSD attached.

Attach a local SSD to confidential vm on gcp, and check the related symlinks,
`/dev/nvme0n1` is local ssd disk, and has the expected symlink `google-${ID_SERIAL_SHORT}`
```
~]# bash /usr/lib/udev/google_nvme_id -d /dev/nvme0n1
ID_SERIAL_SHORT=local-nvme-ssd-0
ID_SERIAL=Google_EphemeralDisk_local-nvme-ssd-0
~]# ls -l /dev/disk/by-id/google-local-nvme-ssd-0
lrwxrwxrwx. 1 root root 13 May 16 05:55 /dev/disk/by-id/google-local-nvme-ssd-0 -> ../../nvme0n1
```
`/dev/nvme1n1` is nvme disk, and does not have expected symlink `google-${ID_SERIAL_SHORT}`, this is expected as the issue is not fixed yet.
```
~]# bash ./google_nvme_id -d /dev/nvme1n1
./google_nvme_id: line 65: warning: command substitution: ignored null byte in input
ID_SERIAL_SHORT=persistent-disk-0
ID_SERIAL=Google_PersistentDisk_persistent-disk-0
~]# ls /dev/disk/by-id/google-persistent-disk-0
ls: cannot access '/dev/disk/by-id/google-persistent-disk-0': No such file or directory
```

Maybe I can add 1 test (attach a local SSD to confidential vm) and check the 2 nvme disks symlinks, but there is another problem that current CLI only supports [PERSISTENT](https://github.com/coreos/coreos-assembler/blob/main/mantle/platform/api/gcloud/compute.go#L77) disk, this mean I should add CLI to support?
