### ISSUE TITLE
Enable libostree automatic early pruning

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#1495]
libostree now supports a new feature called automatic early pruning: https://github.com/ostreedev/ostree/pull/2847. This allows nodes with not enough space in `/boot` to store the transient third kernel and initrd to still upgrade. It will allow us to make progress on https://github.com/coreos/fedora-coreos-tracker/issues/1247, https://github.com/coreos/fedora-coreos-tracker/issues/1446, and https://github.com/coreos/fedora-coreos-tracker/issues/1467.

However, the feature is not yet enabled by default. Consider enabling it in FCOS. We may decide to enable it only on non-x86_64 to start since that's where it's most needed and then eventually enable it everywhere (and eventually hopefully we can enable it by default upstream too).

**Comment by cgwalters** [comment]
We could enable it just in `next` or `rawhide` I guess too?

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://discussion.fedoraproject.org/t/fedora-coreos-meeting-minutes-2023-05-24/83075).

```
13:17:14* dustymabe | #agreed We'll enable ostree autopruning for aarch64 in next for 
                    | at least 3 cycles (6 weeks) then promote to testing. We'll  
                    | enable it for ppc64le right away for the streams that we decide
                    | to release ppc64le for. 
```

**Comment by dustymabe** [comment]
This should handle selectively enabling autopruning https://github.com/coreos/fedora-coreos-config/pull/2435

**Comment by dustymabe** [comment]
In https://github.com/coreos/fedora-coreos-config/pull/2435 we enabled libostree automatic early pruning for ppc64le and for aarch64 (in F39+), which will get a healthy dose of testing when `next` switches over to F39 around beta time.

After these test cycles complete hopefully we'll enable the early pruning by default in `ostree` upstream and we won't carry any enablement config any longer.

I'll close this out since there is no further work for us to do here.
