### ISSUE TITLE
Fix rpm-ostree CVE-2024-2905 (world-readable `/etc/[g]shadow[-]`)

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#1705]
- https://github.com/coreos/rpm-ostree/security/advisories/GHSA-2m76-cwhg-7wv6
- https://access.redhat.com/security/cve/CVE-2024-2905

**Comment by travier** [comment]
Some historical links for a closely related fix:
- https://github.com/coreos/fedora-coreos-config/pull/1003
- https://github.com/coreos/fedora-coreos-tracker/issues/829

**Comment by dustymabe** [comment]
Copying some info forward:

The underlying issue is related to https://github.com/coreos/rpm-ostree/pull/4503, which was first released in rpm-ostree [v2023.6](https://github.com/coreos/rpm-ostree/releases/tag/v2023.6).

That version was never released in Fedora, but [v2023.7](https://github.com/coreos/rpm-ostree/releases/tag/v2023.7) was first in [bodhi stable](https://bodhi.fedoraproject.org/updates/FEDORA-2023-4f4ef60b05) in early September 2023. 

Fedora CoreOS versions were affected when `rpm-ostree-2023.7-1` entered our CoreOS Assembler build container. Tracing our `testing-devel` stream the last good and first bad were:

- `38.20230904.20.0` -> good
- `38.20230906.20.1` -> bad 

So the bad version of `rpm-ostree` got into CoreOS Assembler ~09/06/2023. Based on this I tested and here are the last good and first bad for each of our production streams:

- `stable`
    - `38.20230819.3.0` -> good               
    - `38.20230902.3.0` -> bad  
- `testing`
    - `38.20230902.2.0` -> good
    - `38.20230902.2.1` -> bad 
- `next`
    - `38.20230902.1.0` -> good
    - `38.20230902.1.1` -> bad

**Comment by dustymabe** [comment]
PRs for `stable`, `testing-devel`, and `next-devel`:

- https://github.com/coreos/fedora-coreos-config/pull/2951
- https://github.com/coreos/fedora-coreos-config/pull/2950
- https://github.com/coreos/fedora-coreos-config/pull/2949

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `40.20240408.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `39.20240407.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `39.20240322.3.1`.
