### ISSUE TITLE
`/boot/efi` is `unlabeled_t` since version 40.20240504.3.0

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#1771]
### Describe the bug

`/boot/efi` is `unlabeled_t` since 40.20240504.3.0.

Bisect results:
- 40.20240416.3.1 is good
- 40.20240504.3.0 is bad
- 40.20240519.3.0 is bad
- 40.20240616.3.0 is bad

### Reproduction steps

Boot FCOS. Run:

```
ls -alhZ /boot
```

### Expected behavior

`/boot/efi` is correctly labeled as `boot_t` (unmounted) and `dosfs_t` (mounted).

### Actual behavior

`/boot/efi` is `unlabeled_t` (unmounted).

### System details

N/A

### Butane or Ignition config

```yaml
None
```

### Additional information

This is impacting us in Rawhide as the bootupd_t SELinux domain is no longer permissive there: https://bugzilla.redhat.com/show_bug.cgi?id=2300306

**Comment by travier** [comment]
As 40.20240504.3.0 is the first bad version, this points to https://github.com/coreos/fedora-coreos-tracker/issues/1653 introducing this issue.

**Comment by travier** [comment]
Looks like the SELinux label is missing in https://github.com/coreos/coreos-assembler/blob/main/src/osbuild-manifests/coreos.osbuild.x86_64.mpp.yaml#L164..L168 maybe?

**Comment by travier** [comment]
Looks like there is no option for it in https://github.com/osbuild/osbuild/blob/main/stages/org.osbuild.mkdir.meta.json. I could only find https://github.com/osbuild/osbuild/blob/main/stages/org.osbuild.selinux.meta.json but that's too broad.

**Comment by HuijingHei** [comment]
And files under `/sysroot` are `unlabeled_t`, `/sysroot/.aleph-version.json` and `/sysroot/.coreos-aleph-version.json` are created by https://github.com/osbuild/osbuild/blob/main/stages/org.osbuild.ostree.aleph#L102
```
[root@cosa-devsh ~]# ls -alZ /sysroot/
total 8
drwxr-xr-x.  4 root root system_u:object_r:unlabeled_t:s0   93 Aug  1  2022 .
drwxr-xr-x. 12 root root system_u:object_r:root_t:s0      4096 Jul 29 18:54 ..
-rw-r--r--.  1 root root system_u:object_r:unlabeled_t:s0  206 Aug  1  2022 .aleph-version.json
lrwxrwxrwx.  1 root root system_u:object_r:unlabeled_t:s0   19 Aug  1  2022 .coreos-aleph-version.json -> .aleph-version.json
drwxr-xr-x.  2 root root system_u:object_r:unlabeled_t:s0    6 Jul 29 18:54 boot
drwxr-xr-x.  5 root root system_u:object_r:unlabeled_t:s0   62 Jul 31 13:46 ostree
```

**Comment by cgwalters** [comment]
This is another one that would get fixed once FCOS rebases on Fedora bootc, because bootc gets this correct.

**Comment by travier** [comment]
How so? Is something done in https://github.com/osbuild/bootc-image-builder to account for that?

**Comment by cgwalters** [comment]
> How so? Is something done in https://github.com/osbuild/bootc-image-builder to account for that?

Conceptually, the role of osbuild with *bootc* is just to set up the partitions and an empty filesystem, and invoke` bootc install to-filesystem`, which is what I want anaconda to do as well with https://github.com/rhinstaller/anaconda/discussions/5197

This takes over a lot of the role of all the currently split-up micro "stages" in osbuild. See for example the giant discussion of a [custom aleph stage](https://github.com/dustymabe/osbuild/pull/10#). Instead, that's just hardcoded in bootc, osbuild is not involved.

**Comment by cgwalters** [comment]
The simplest way to say it is the bootc vision is that the *container image* and container technology is the center of gravity, the north star, the default source of truth, the technological heart. If you want to change how the bootloader gets installed, you change the contents of the container - not some external tool.

**Comment by travier** [comment]
So that would be using https://github.com/osbuild/osbuild/blob/main/stages/org.osbuild.bootc.install-to-filesystem. That could be a future improvement / unification point for the osbuild part.

**Comment by travier** [comment]
We'll still have to work on a script to locally fix existing installations.

**Comment by achilleas-k** [comment]
Ok, I see there's already an `org.osbuild.ostree.selinux` stage here:
https://github.com/coreos/coreos-assembler/blob/main/src/osbuild-manifests/coreos.osbuild.x86_64.mpp.yaml#L244-L247

But the partitions aren't mounted for that stage, so perhaps that's what's missing.

**Comment by jlebon** [comment]
AIUI, the situation currently is that:
- nodes born on new enough f40 has missing labels, but bootupd still works because the `bootupd_t` policy is permissive
- nodes born on f41+ has missing labels, and bootupd doesn't work because the `bootupd_t` policy is no longer permissive

So one path forward is to:
1. Fix the labeling in new disk images, definitely before f41 hits `next`.
2. Do a barrier release with a script that fixes unlabeled directories on affected machines. At the latest this barrier release needs to be before the rebase to f41, but could be before. We do already do a barrier release during rebases, so could combine it.

**Comment by travier** [comment]
Not that we'll need to keep this workaround fixup script until we've fixed our osbuild pipeline / boot images.

**Comment by jlebon** [comment]
When fixing this, we should also fix https://github.com/coreos/fedora-coreos-tracker/issues/1772 in the same barrier code.

**Comment by yasminvalim** [comment]
We discussed this in our community meeting today. You can review the details of our discussion [here](https://meetbot.fedoraproject.org/meeting-1_matrix_fedoraproject-org/2024-08-28/fedora-coreos-meeting.2024-08-28-16.26.log.html).

**Comment by dustymabe** [comment]
I don't think this problem is specific to us. Here is a RHEL 10 candidate image `rhel-guest-image.qcow2`:

```
[root@localhost ~]# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sda      8:0    0   30G  0 disk 
├─sda1   8:1    0    1M  0 part 
├─sda2   8:2    0  200M  0 part /boot/efi
└─sda3   8:3    0 29.8G  0 part /
sr0     11:0    1  368K  0 rom  
[root@localhost ~]# 
[root@localhost ~]# 
[root@localhost ~]# ls -ldZ /boot/efi
drwx------. 3 root root system_u:object_r:dosfs_t:s0 16384 Dec 31  1969 /boot/efi
[root@localhost ~]# umount /boot/efi
[root@localhost ~]# ls -ldZ /boot/efi
                                                                               
drwxr-xr-x. 2 root root system_u:object_r:unlabeled_t:s0 6 Sep  6 04:33 /boot/efi
```

and here is Fedora 40 IoT (from the raw disk image):

```
[root@localhost ~]# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
zram0  251:0    0  3.8G  0 disk [SWAP]
vda    252:0    0    4G  0 disk 
├─vda1 252:1    0  501M  0 part /boot/efi
├─vda2 252:2    0    1G  0 part /boot
└─vda3 252:3    0  2.5G  0 part /var
                                /sysroot/ostree/deploy/fedora-iot/var
                                /usr
                                /etc
                                /
                                /sysroot
[root@localhost ~]# ls -ldZ /boot /boot/efi
drwxr-xr-x. 7 root root system_u:object_r:boot_t:s0   4096 Apr 22 20:11 /boot
drwx------. 3 root root system_u:object_r:dosfs_t:s0 16384 Jan  1  1970 /boot/efi

[root@localhost ~]# umount /boot/efi
[root@localhost ~]# ls -ldZ /boot/efi
drwxr-xr-x. 2 root root system_u:object_r:unlabeled_t:s0 4096 Apr 22 20:11 /boot/efi
```


@achilleas-k I don't really think there is a way to get the labels correct on the root of a mounted filesystem today using OSBuild is there?

**Comment by dustymabe** [comment]
It's also worth noting I doubt other editions observe a problem because (I think) we are the only ones that default to not having `/boot/efi` mounted on boot.

**Comment by dustymabe** [comment]
opened https://github.com/osbuild/osbuild/issues/1877 to discuss further a fix in osbuild itself.

**Comment by achilleas-k** [comment]
Expanding a bit from the issue Dusty linked to:

The core of the issue, as I understand it, is that with the way the image is built, the filesystem mountpoints _on the parent filesystem_ (in this case `/boot/efi` on `/`, i.e. the node itself when `/boot/efi` is not mounted) are never labelled because they're never "exposed" during `setfiles` or copying.  This isn't a problem usually because mountpoints at build time *and* at runtime are always hidden by the mounted filesystem itself.

This is a problem for the CoreOS image because `/boot/efi` isn't mounted on boot (as Dusty clearly described above).  I assume the reason this wasn't an issue before osbuild is because `/boot/efi` was created "in place", so to speak.  The build scripts were creating the OS tree directly, and creating `/boot/efi` on an selinux enabled system will apply the labels/contexts for that path on creation (am I getting this right?).  On the other hand osbuild is running `mkdir /some/runtime/mountpoint/boot/efi` before mounting the EFI filesystem to copy files into it (no labelling).

I don't know if this should be considered a bug in osbuild or something the image definition itself should take care of.  We could certainly make it easier to do what's needed with mechanisms in osbuild, but I wouldn't make it an implicit action (e.g. applying labels automatically when `mkdir`ing mountpoints).

We have a limitation now in the selinux stage, it wont run `setfiles` on a mounted tree, but that's an easy fix.  With that, I would leave it up to the image definition to do the right thing with the tooling, for example:

1. Create disk (`truncate`)
2. Partition disk (`sfdisk`)
3. Create filesystems (`mkfs`)
4. *NEW*: Create mountpoints on each filesystem separately (`mkdir`)
5. *NEW*: Apply selinux labels to each filesystem mountpoint (`setfiles`)

Step 5 is the important step.  It can be done explicitly:
```json
{
  "type": "org.osbuild.selinux",
  "options": {
    "labels": {
      "/efi": "<labels for /boot/efi>"
    }
  },
  "mounts": [ "mount /boot filesystem at <mount root>" ],
  "devices": { disk device }
}
```

or implicitly with a full relabeling (better long term):
```json
{
  "type": "org.osbuild.selinux",
  "options": {
    "file_contexts": "etc/selinux/targeted/contexts/files/file_contexts"
  },
  "mounts": [
    "mount / filesystem at <mount root>",
    "mount /boot filesystem at <mount root>/boot"
  ],
  "devices": { disk device }
}
```

Generalising this isn't really something that fits into osbuild itself, it's a piece of logic that belongs in the image definition or a manifest generator like osbuild-mpp and osbuild/images.  But osbuild's selinux stage should support the workflow.

**Comment by dustymabe** [comment]
replied over in https://github.com/osbuild/osbuild/issues/1877#issuecomment-2353997726

**Comment by dustymabe** [comment]
The first part of this (fix/workaround in images) was delivered in https://github.com/coreos/coreos-assembler/pull/3885

The second part of this (fixing existing systems on upgrade with a migration script) will be done in https://github.com/coreos/fedora-coreos-config/pull/3150

**Comment by dustymabe** [comment]
- fixed disk images in https://github.com/coreos/coreos-assembler/pull/3885
- fixed upgrading systems in https://github.com/coreos/fedora-coreos-config/pull/3150

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `41.20241006.1.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `40.20241006.2.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `40.20241006.3.0`.
