### ISSUE TITLE
Butane release container tag not yet updated to 0.23.0

### ISSUE THREAD

**Issue by Nemric** [coreos/fedora-coreos-tracker#1848]
I was "wilfing" (What Was I Looking For?) today when I saw the latest Butane spec v1.6.0
Well, I did the update as fast as possible : https://github.com/Relativ-IT/Butane-Schemas
And did upgrade my butane configs to latest spec ... but it looks like the config transpiler `quay.io/coreos/butane:release` is not yet up to date ^^
`Error translating config: No translator exists for variant fcos with version 1.6.0`

regards :)

**Comment by jbtrystram** [comment]
It looks like it's WIP :) https://github.com/coreos/butane/issues/550

**Comment by Nemric** [comment]
I using the latest (vs release) images now, it works ^^
Will close the issue when release will be out ;)

**Comment by Nemric** [comment]
As my ign files are now on v3.5.0 specs, and as next week a new Fcos should come (stable, testing and next) will new ignition be included in them ?

**Comment by hrismarin** [comment]
> As my ign files are now on v3.5.0 specs, and as next week a new Fcos should come (stable, testing and next) will new ignition be included in them ?

Since I was recently asking relatively the same questions, I'll bring what I (hopefully) learned here. Please correct me if I'm wrong.

Ignition `v2.20.0` has now been released and the `3.5.0` config specs have been marked as stable, see https://github.com/coreos/ignition/releases/tag/v2.20.0. Because Ignition needs to go first, there is a window between where Ignition got stabilized but not yet Butane. It looks like the Butane docs page has now been updated to match the latest specs (if that's what @Nemric  means) and Butane has been stabilized but not yet released.

**Comment by travier** [comment]
Thanks for the report. The releases and stabilisation is indeed still in progress.

Unless if you are using an s390x system (unlikely given our usage numbers), there are no changes in this release for other architectures so there is no urgency to update: https://coreos.github.io/butane/upgrading-fcos/#from-version-150-to-version-160

**Comment by Nemric** [comment]
> Ignition `v2.20.0` has now been released and the `3.5.0` config specs have been marked as stable, see https://github.com/coreos/ignition/releases/tag/v2.20.0. Because Ignition needs to go first, there is a window between where Ignition got stabilized but not yet Butane. It looks like the Butane docs page has now been updated to match the latest specs (if that's what @Nemric means) and Butane has been stabilized but not yet released.

Yes that's what I meant ^^
Well, you're IDE (like vscode or sublime) that use the json schema store for bu/yaml files is up to date for v1.6.0 ;)

**Comment by Nemric** [comment]
then close ...
