### ISSUE TITLE
Move the zincati binary under /usr/libexec

### ISSUE THREAD

**Issue by arithx** [coreos/fedora-coreos-tracker#244]
It is currently not intended for the `zincati` binary to be actually ran interactively by users. As such I think it would make sense to move the binary under `/usr/libexec` and update the unit to that location.

**Comment by lucab** [comment]
At the moment `zincati` is daemon-only, and its TOML configuration is the single fully-declarative source of truth. However, all the daemon logic is scoped under the `zincati agent` subcommand, so that if in the future we want to add an interactive client we have room for that (as additional subcommands).

As such, at the moment there are no interactive subcommands and we can freely move the binary out of PATH. We can also move it back at any point in future, if we need to.

/cc @rfairley

**Comment by rfairley** [comment]
Installing the `zincati` binary to `/usr/libexec, until user-facing commands are added, sounds good to me. We can also do the same for `fedora-coreos-pinger`.

The way the crate is packaged right now, with the `%cargo_install` RPM macro, `cargo install` is used with `install.root` in the Cargo config set to `%{buildroot}/usr`. It doesn't look like there is currently a way in Cargo to install binaries to somewhere other than the `bin` directory of the specified installation root (https://doc.rust-lang.org/cargo/commands/cargo-install.html#cargo-install). However, an easy way around this is to just `mv` the binary from `/usr/bin/zincati` to `/usr/libexec/zincati` after `cargo install` is finished. Given `zincati` is a single binary, this shouldn't cause issues once the path in the unit is updated (just tried it locally now).

@ignatenkobrain do you see any other issues with this (or know of a better way than moving the binary post-`cargo install`)?

**Comment by ignatenkobrain** [comment]
In Fedora we just do `mv` for things like this…
