### ISSUE TITLE
Installer ISO is confusing

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#253]
Steps to reproduce:
1. Go to the [Fedora CoreOS download page](https://getfedora.org/coreos/download/).
2. Download installer ISO.
3. Boot installer ISO.  Choose `Install Fedora CoreOS` menu entry.
4. Find yourself at the initramfs emergency shell: 
![Screenshot from 2019-08-12 16-33-05](https://user-images.githubusercontent.com/361374/62896375-ee86f000-bd1e-11e9-94e3-78a1837dd145.png)
5. Scroll back, to figure out what's going on: 
![Screenshot from 2019-08-12 16-33-18](https://user-images.githubusercontent.com/361374/62896399-fd6da280-bd1e-11e9-9771-24ce9fa86f17.png)

Net result: if someone follows the natural flow for installing an OS, they'll receive an error message that looks like a problem with the installer, followed by a shell prompt which isn't obviously running in a restricted environment.

The download page doesn't indicate that special install procedures are required.  The [main page](https://getfedora.org/en/coreos/) does link to the [getting started guide](https://docs.fedoraproject.org/en-US/fedora-coreos/getting-started/), which [links](https://docs.fedoraproject.org/en-US/fedora-coreos/getting-started/#_installing_on_bare_metal) to the [coreos-installer repo](https://github.com/coreos/coreos-installer/), which has a lot of text about "testing" installs.

The proper technical fix is probably #203, but docs improvements are also needed.

**Comment by tuan-hoang1** [comment]
I think this is more of an docs issue rather than the technical issue of moving coreos-installer out of initramfs. Even if you get a shell (by booting in a tmpfs-based root), they still need to invoke coreos-installer program with Ignition and raw image URLs - which they need to consult the docs. So both case, users need to rtfm.

Moving coreos-installer out of initramfs to a tmpfs-based root makes sense, I agree, iff user want to run something else (user arbitrary code, etc.) after the coreos-installer finishes.

**Comment by bgilbert** [comment]
Docs improvements are still (always) needed, but we've eliminated the misleading/counterintuitive behavior described here.  I'll close.
