### ISSUE TITLE
fcct-online: location to deploy

### ISSUE THREAD

**Issue by zonggen** [coreos/fedora-coreos-tracker#260]
The web app for fcct (https://github.com/zonggen/fcct-online) is ready to be deployed, though just want to make sure / discuss that fcos openshift cluster is the right place to deploy it (https://console.apps.ci.centos.org:8443/console/).

**Comment by dustymabe** [comment]
Regarding CentOS CI: I think we should probably leave that cluster just for our builds and not host any externally facing applications there.

Since this is a non-critical application maybe a good place for this would be a `fedora-coreos-fcct-online` project within Fedora's [new communishift offering](https://fedoraproject.org/wiki/Infrastructure/Communishift?rd=Infrastructue/Communishift). If everyone agrees then I can help get that set up.

**Comment by dustymabe** [comment]
cc @bgilbert @bstinsonmhk @lucab

**Comment by zonggen** [comment]
New to the CentOS CI, but I think Dusty made a good point. Communishift sounds like more suitable for fcct-online.

**Comment by dustymabe** [comment]
I made a request to get a group owned space inside communishift to see if we can use it for managing applications like this: https://pagure.io/fedora-infrastructure/issue/8218

tagging with meeting so I can FYI and people can bring up any concerns.

**Comment by zonggen** [comment]
Thanks for creating the issue. :+1:

**Comment by bgilbert** [comment]
We're not actively pursuing fcct-online for now, so I'll close this out.  Thanks for working on it.  :heart:
