### ISSUE TITLE
Persist network configuration when using bond configuration

### ISSUE THREAD

**Issue by spaced** [coreos/fedora-coreos-tracker#288]
Given:
Boot via pxe coreos-installer using dracut arguments for configure a fix `IP` and `bond` configuration
```
     ip=10.42.0.100::10.42.0.5:255.255.255.0:mynode.home.local:bond0:off
     bond=bond0:eth4,eth5:mode=4
     nameserver=10.42.0.1
     rd.neednet=1
     coreos.inst=yes
...
```
expected:
network configuration are persisted.

but:
After first boot everything looks fine, but after second reboot network settings are lost

**Comment by ajeddeloh** [comment]
This is intentional, though we definitely need to document this better. Networking configuration should be done by writing out NetworkManager configs via the FCCT `storage.files` section.

All the configuration is meant to be in the Ignition config. However, the installer needs network and doesn't consume an Ignition config, so it allows networking options on the kernel cmdline. Ignition also needs networks and runs on first boot, so we copy the networking options from the installer for it to use on first boot, but then delete it afterwards. The goal is to prevent kernel command line options from becoming a source of configuration.

**Comment by spaced** [comment]
this will solve my issue. tnx.

**Comment by dustymabe** [comment]
Note that what the requestor was asking in this issue now works like he wanted. See https://docs.fedoraproject.org/en-US/fedora-coreos/sysconfig-network-configuration/ for more information.
