### ISSUE TITLE
Should OSTree be used at all?

### ISSUE THREAD

**Issue by redbaron** [coreos/fedora-coreos-tracker#35]
Hi All,

I've been a happy user of Fedora Atomic Workstation and really like rpm-ostree feature. Having said that, I can't find any discussion why ostree (or rpm-ostree) should be used for FCOS?  With it's Ignition based configuration and read-only /usr what is the benefit of having ostree?

**Comment by ajeddeloh** [comment]
The A/B USR partition scheme had a few problems. A lot of software isn't packaged in a way to support it (e.g. look at all the cruft in coreos-overlay) which means more work maintaining that. With OSTree and rpm-ostree we can piggy-back off of all the work that's already been done packaging things for it. It also means you can't RAID or otherwise mess with the USR partitions which would be possible with OSTree.

We've also talked about using rpm-ostree's package layering to more elegantly handle multiple docker/crio/kubernetes versions (filling the role torcx fills today). Granted, there's still a lot left there to figure out.

Another (pretty minor since disk is "cheap") perk is that OSTree doesn't need 2x the space for supporting rollbacks.

OSTree is certainly a little more complex than the A/B scheme, but it does give us a cleaner solution to a lot of the problems we've faced.

**Comment by mskarbek** [comment]
A lot of that "figuring out" could be simply solved with ZFS boot environments like in FreeBSD. :D 
I know its extremely wishful thinking of a single "fanatic" but RH should at this point just pay Oracle to relicense ZFS to GPL.

**Comment by mskarbek** [comment]
@cgwalters ofc it's different. With ZFS snapshots, clones and send/receive functionality I'm building infrastructure for a fleet of hosts to do painless, atomic updates. You just send an incremental snapshot of a rootfs and you are done. Installation? Bootstrap pool on a disk and just ship the whole dataset. Rollbacks? Promoting clones and rolling back snapshots.
Sadly I was unable to go to the FLOCK because I wanted to present that work.
Problematic in that scenario is adding own things - rpm layering in ostree equivalent is impossible for me right now.
I am aware what ostree do very good and what are the differences in both approaches. This is why I'm playing with both and follow Atomic Host/FCOS work.

**Comment by dustymabe** [comment]
In the [meeting on wednesday](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/WTEKMCC6KHDWHPRZDTC4YLTX4LN3GCNB/) we discussed this. There are several reasons why we like the OSTree/RPM-OSTree approach but at a high level it comes down to the fact that OSTree is a healthy upstream project that is being used by many projects (endless OS, flatpak, embededed systems (I forget the name of the project), Atomic Host, Silverblue, Fedora IoT) and within the group we have some of the core contributors of RPM-OSTree and OSTree, which means we can get features implemented and bugs fixed relatively quickly.

@mskarbek - you were in the meeting. Any other points you'd like to make?

**Comment by mskarbek** [comment]
@dustymabe nope. :) Choosing OSTree is fully understandable.

**Comment by redbaron** [comment]
It make sense. I hope it will be included in FCOS release notes along side of many other "What's new and why it is so"

**Comment by c4milo** [comment]
was ostree finally introduced? I also think it is a superior approach.

**Comment by dustymabe** [comment]
Yes Fedora CoreOS is based on rpm-ostree/ostree. You can get started here: https://getfedora.org/en/coreos/
