### ISSUE TITLE
Enable offline bare metal installations

### ISSUE THREAD

**Issue by imranrazakhan** [coreos/fedora-coreos-tracker#352]
I prepared ignition embeded ISO file with below command

```
sudo podman run --pull=always --privileged --rm \
    -v /dev:/dev -v /run/udev:/run/udev -v .:/data \
    quay.io/coreos/coreos-installer:release \
    iso embed /data/fedora-coreos-31.20200113.3.1-live.x86_64.iso -c /data/config.ign -f

```
On booting from this ISO on bash its ask for user/pass and i provided user/pass which i mentioned in ignition file after that i tries to install on disk but its giving error

```
$ coreos-installer install /dev/sda
Downloading stable image and signature
Error: fetching stream metadata
Caused by: https://builds.coreos.fedoraproject.org/streams/stable.json: timed out
```

So does i missed anything? i am expecting now ISO contain all binaries so why its trying to pull from internet?

**Comment by jlebon** [comment]
> i am expecting now ISO contain all binaries so why its trying to pull from internet?

The installer still needs to pull down the actual bare metal disk image to use. You can also cache the image and its signature on your local network and pass it to `coreos-installer install` using `--image-url`.

There's been work to include the metal image in the ISO (that's https://github.com/coreos/coreos-assembler/pull/928). Though following the discussions from there, it'd be really nice if we could have our cake and eat it too: be able to install the metal image matching the version of the ISO without having to include the whole image itself.

**Comment by jlebon** [comment]
Following up on [Colin's comment](https://github.com/coreos/coreos-assembler/pull/928#issuecomment-556410010) there:

> Binary deltas would be harder.

Hmm, would be interesting though to investigate this. Binary diffing the metal image against the squashfs and checking how large that delta file actually is. The big wrench though is that the squashfs is compressed. Would be cool if there was a way to stream uncompress it + apply the delta + write it to disk.

**Comment by imranrazakhan** [comment]
@jlebon thanks for detailed updates, we are evaluating CoreOS for IOT based solution, which mostly get deployed on remote places with no internet. It would be nice to install CoreOS offline or there should be option to package all in one place so remote worker with less IT knowledge could install it.

**Comment by jlebon** [comment]
One thing we could easily do short-term is to start building and shipping the fulliso ISOs... Though then we go back to having a dedicated "installer ISO" separate from the live ISO.

Another option is enhancing `coreos-installer iso embed` to also take a e.g. `--disk-image` switch. Though it wouldn't be as lightweight an operation as just injecting the Ignition config.

**Comment by imranrazakhan** [comment]
>> Another option is enhancing coreos-installer iso embed to also take a e.g. --disk-image switch

This would be good option and we have to do it once doesn't matter it's light operation or not.

**Comment by keithy** [comment]
--image-url does take a file:// so the raw can be available locally. 
I use the ISO, with a standard embedded ignition "installer.service" that mounts a USB key and runs core-osinstaller with the ignition (and raw image) that is on the USB Key.
This means that for me a bare metal install is both a CD and a USB Key.
http://github.com/keithy/ign-embed

**Comment by keithy** [comment]
Why not just embed a directory of possible resources.
This would allow a variety of novel soltions.
 
Firstly the image can be included as requested above. fcct can be embedded, such that the installation service can run from yaml, and clever scripts can be provided.

**Comment by imranrazakhan** [comment]
+1 for embedding directory of possible resources.

Currently with CentOS Kickstart we add custom directory(which contains firmware for other devices) under isolinux and on first boot we connect those devices and tftp this firmware.

Similarly we want to copy firmware with ignition to other connected devices. So similar kind of use cases can be addressed with embedding directory.

**Comment by lucab** [comment]
I'd like to take a step back and focus on one key part here below.

> we are evaluating CoreOS for IOT based solution, which mostly get deployed on remote places with no internet. It would be nice to install CoreOS offline

For this usecase, you likely want to pre-image your disks on a separate dedicated machine. This is what `coreos-installer install --ignition $foo --image-file $bar` do.
This can be run in any environment where you have storage available for keeping state (i.e. the final Ignition config, the OS image, and whatever custom logic you may need).

However
 1. the live-ISO is not the best choice as an environment for that. It is meant to provide a minimal live FCOS, without state persistence. For additional resources, it will need an additional disk (like @keithy's CD+USB approach). At that point, any other (non FCOS live-ISO) system of your choice is an equally good choice.
 2. I'm wary of bending the live-ISO or coreos-installer into embedding more arbitrary stuff. For maintenance and scoping reasons, I'd like not to the derail any of those two into the "kit for building your own Linux" direction.
 3. please beware that the "remote offline IoT node" usage is not directly on the radar for FCOS. While it may work with some specific hacks at some point, all the components (initrd, Ignition, Zincati, installer, etc.) are designed to mostly expect always-on networking.

**Comment by imranrazakhan** [comment]
>> Another option is enhancing coreos-installer iso embed to also take a e.g. --disk-image switch. Though it wouldn't be as lightweight an operation as just injecting the Ignition config.

@lucab but still @jlebon suggested idea to embed raw image is good

**Comment by keithy** [comment]
I still think it makes sense to embed a directory of resources, even just to support basic ignition functionality.

This then provides a progression from (FCOS.iso+USB Stick) to (FCOS.iso + embedded)

Although you can use any other live ISO these will not have an embed feature at all.

**Comment by jlebon** [comment]
> This would be good option and we have to do it once doesn't matter it's light operation or not.

Maybe lightweight wasn't the right word. Embedding the Ignition config right now is done [using some clever tricks](https://github.com/coreos/coreos-installer/blob/master/doc/iso-embed-ignition.md#technical-details). Trying to embed arbitrary files of arbitrary sizes would likely require essentially re-creating the ISO, which is a lot more awkward.

> Why not just embed a directory of possible resources.

Possibly, though remember all this has to be able to fit into RAM later on. Optimizing for the metal image like discussed above would be neat, but only if it doesn't change the constraints too much. Overall, I agree with @lucab on keeping that functionality narrow and work on trying to solve common use cases at a higher-level.

**Comment by feklar7** [comment]
> 
> 
> +1 for embedding directory of possible resources.
> 
> Currently with CentOS Kickstart we add custom directory(which contains firmware for other devices) under isolinux and on first boot we connect those devices and tftp this firmware.
> 
> Similarly we want to copy firmware with ignition to other connected devices. So similar kind of use cases can be addressed with embedding directory.

This is exactly our use case. We do this with Atomic: add OCI images and other scripts to the ISO, and a custom kickstart copies those resources and OCI images to the installed file system. 

Once we modify the ISO, we respin the ISO with genisoimage.

We need to do all of this because our target systems are all air gapped. They're individual computing nodes (some can be completely isolated, i.e. zero networking). 

I haven't been able to find how to copy files from ISO to the target file system.

**Comment by imranrazakhan** [comment]
@jlebon any update which option will be available in  

>> enhance coreos-installer iso embed to also take a e.g. --disk-image switch for raw

or

>> enhance coreos-installer iso embed to embed directory of possible resources?

**Comment by zaheer965** [comment]
+1 for enhance coreos-installer iso embed to also take a e.g. --disk-image switch for raw

@keithy Cant you use storage (files and directory) of ignition file with usb for other resources? (correct me if my understanding is not correct)

**Comment by keithy** [comment]
I can indeed, because I have chosen to adopt the ISO + USB Stick model; this satisfies my needs (except that having the cd image download directly from the USB is currently painfully slow)

**Comment by dustymabe** [comment]
we discussed this at the [FCOS community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/OIKQKNPJXSD7DCFZV3IRETDTKG247UNH/). This ticket has a few different feature requests, but we are choosing to focus on the following feature request:

- including the bare metal disk image in the live ISO by default in order to support offline installs

We are going to do some investigation into the feasibility of the above item to see if it will be easy to do without compromising the live ISO (i.e. not used as an installer) workflow and also without increasing the size of the live ISO by a large margin.

All other features discussed in this ticket should be discussed in new tickets that are scoped directly to those features.

**Comment by linquize** [comment]
How large will the image grow?

**Comment by jlebon** [comment]
OK, https://github.com/coreos/coreos-installer/pull/187 is a working proof-of-concept on one way we could enable offline updates without really changing memory requirements. Chatting with @dustymabe, we're also brainstorming ways to directly use the metal image as another way to resolve this.

**Comment by jlebon** [comment]
After more discussions on this topic, we are going to go with the approach in https://github.com/coreos/coreos-installer/pull/187.

I renamed the title of this issue to reflect this.

**Comment by jlebon** [comment]
Just for posterity: an alternative we considered was including the bare metal image directly in the live ISO instead of the root squashfs. Some issues discussed with this were:
- We would still want a squashfs'ed image (with the metal image inside) because we don't want to store the full image uncompressed in the initrd. This has two issues: (1) lower compression ratio due to compressing at the block level instead of the filesystem level, resulting in, for FCOS, 160M more data, and (2) it doesn't elegantly solve the "stage 2" problem (https://github.com/coreos/fedora-coreos-tracker/issues/390) because it requires users to now run `mksquashfs` on the downloaded metal image.
- It requires a complex mount setup and hierarchy to first loop mount the squashfs, then loop mount the metal image contained inside using e.g. `kpartx` or `losetup -P` to mount partition offsets.

Instead, we're going to try to solve the two somewhat related but separate problems (this issue and #390) independently.

**Comment by dustymabe** [comment]
@jlebon - IIUC the osmet + coreos-installer work that landed in the latest testing release should resolve this issue?

**Comment by jlebon** [comment]
Yes, this is fixed in the latest testing release!

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `31.20200505.2.0`.  Please try out the new release and report issues.

**Comment by dustymabe** [comment]
You do an offline install by simply not specifying a stream or image url like so:

```
sudo coreos-installer install /dev/sda --ignition-file example.ign
```

The installer will default to using the local artifacts (on this ISO) and do an install.

**Comment by Cherokee777** [comment]
Ok, so this new "dialect" is grating on me. "Stream" means nothing except for RH or the struggling Centos. 

Some clarity would be nice, as in this case: 'local artifacts'. Yes, the latter is obviously something baked in, but what are they?

 Very much appreciate this "fix" since we live in the real deployment world.  It's still bad, but better.

**Comment by lucab** [comment]
@Cherokee777 for clarity, in this specific context:
 * "streams" refers to FCOS auto-updates, as documented at https://docs.fedoraproject.org/en-US/fedora-coreos/update-streams/
 * "local artifacts" means the OS content in the live ISO. That is, if you are booting from a live ISO and running `coreos-installer` as shown above, it can on the fly reconstruct the disk image to be installed. This is a somehow recent experiment, https://github.com/coreos/coreos-installer/pull/187 has more details on how it works.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `31.20200505.3.0`.
