### ISSUE TITLE
rpm-ostree install golang failed

### ISSUE THREAD

**Issue by skycastlelily2** [coreos/fedora-coreos-tracker#359]
```
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 31.20200113.3.1 (2020-01-14T00:20:15Z)
                    Commit: f480038412cba26ab010d2cd5a09ddec736204a6e9faa8370edaa943cf33c932
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
```

```
[core@localhost ~]$ sudo rpm-ostree install golang
Checking out tree f480038... done
Enabled rpm-md repositories: updates fedora
Updating metadata for 'updates'... done
rpm-md repo 'updates'; generated: 2020-01-27T11:17:05Z
Updating metadata for 'fedora'... done
rpm-md repo 'fedora'; generated: 2019-10-23T22:52:47Z
Importing rpm-md... done
⠁  
Forbidden base package replacements:
  glibc-all-langpacks 2.30-8.fc31 -> 2.30-10.fc31 (updates)
  glibc-common 2.30-8.fc31 -> 2.30-10.fc31 (updates)
  glibc 2.30-8.fc31 -> 2.30-10.fc31 (updates)
This likely means that some of your layered packages have requirements on newer or older versions of some base packages. Doing `rpm-ostree cleanup -m` and `rpm-ostree upgrade` first may help. For more details, sResolving dependencies... done
error: Some base packages would be replaced
```

**Comment by jlebon** [comment]
Did you try the suggestion of `rpm-ostree upgrade` first?

**Comment by dustymabe** [comment]
> Did you try the suggestion of `rpm-ostree upgrade` first?

I'm not sure if we should be suggesting that for FCOS since they should be on the latest node in the graph already (but the latest stable is still behind bodhi updates by some margin). With FCOS we're going to hit this more often because we hold content back to increase stability. We probably need to talk about this more in terms of both FCOS and Fedora Silverblue to see if we can come up with some solutions that help both.

```
rpm-ostree install golang
```
For this particular problem I think we can really say that this should be done in a container (pet container or otherwise), but probably definitely not on the host itself.

**Comment by jlebon** [comment]
Oh whoops, I *totally* thought this was the rpm-ostree issue tracker.
Yes, this should be done in a container. And in fact, even on Silverblue, you generally don't want to build tools directly on your host, but instead in e.g. a [`toolbox`](https://github.com/containers/toolbox/) container.

**Comment by dustymabe** [comment]
@skycastlelily2 can you run golang compilation from inside of a container?

**Comment by skycastlelily2** [comment]
@jlebon I've tried rpm-ostree install golang before I reported this,thanks for your reply.
@dustymabe sure,thanks for your information.
