### ISSUE TITLE
What is the purpose of Ignition

### ISSUE THREAD

**Issue by alpana17** [coreos/fedora-coreos-tracker#366]
There is no concept of Read-only-filesystem as it was in CoreOS
So, what is the purpose of ignition?
Why is it provided?

What can not be done without Ignition?

**Comment by arizvisa** [comment]
Personally I'd imagine the inclusion of Ignition is for backwards compatibility when migrating the current CoreOS users into fedora-coreos.

..and if it's not, it should be.

**Comment by alpana17** [comment]
So you mean that same ignition will work on both CoreOS and Fedora CoreOS?

**Comment by arizvisa** [comment]
I'm not a dever on this project, but as long as you specify the same schema version. Then yep.

**Comment by arizvisa** [comment]
Actually.. comparing the docs at https://docs.fedoraproject.org/en-US/fedora-coreos/fcct-config/ and https://github.com/coreos/ignition/blob/master/doc/configuration-v3_0.md show that they're nearly the same.

**Comment by alpana17** [comment]
Yes, true
But still needs to be re-written as an example:
'local' tag is not supported in 'storage.files' section

I don't know, how that will be handled.

**Comment by arizvisa** [comment]
Your schema is identified by the version under `ignition.version`. So as long as you use the same schema version (or you specify the "correct" version of the schema) that matches what you're using for your definition, ignition will still be able to parse and act on it.

This was one of the things that sucked about `coreos-cloudinit` as due to not having schema versions, an update to the schema would break backwards compatibility (and force you to immediately rewrite it).

Modifications to the schema that are not backwards compatible (i.e. like the 'local' tag for 'storage.files') will more than likely be handled by checking against this field and parsing it differently, as that was what they were doing with the 2.x series before they completely deprecated it.

Historically, you can see how they parsed your json for the 2.x series by looking at the commits for `config/config.go`.
- coreos/ignition@ab34ef755b39284b0f9920b199a1ee9362373893
- coreos/ignition@1ec0e6e1b0cb47edb5344da5cc29fc026bdf5e26

This pattern will be the same for the rest of the minor versions for 3.x and then most likely the same while users transition to the next major version.

**Comment by jlebon** [comment]
> There is no concept of Read-only-filesystem as it was in CoreOS

There is. Notably, `/usr` is read-only by default. :) Check out this blog post for the design philosophy behind Fedora CoreOS and where Ignition fits: https://fedoramagazine.org/introducing-fedora-coreos/.

Re. CL to FCOS migration, see https://github.com/coreos/fedora-coreos-docs/pull/31.

**Comment by jlebon** [comment]
I'm going to close this, but feel free to re-open if there's something we should fix here.

**Comment by bgilbert** [comment]
One clarification: the versions of Ignition in CL and FCOS do not support any of the same schema versions, so an explicit migration will be required.  The contents of Ignition configs will also need to change to match the filesystem layout, etc., of FCOS.
