### ISSUE TITLE
Add fcct to initrd

### ISSUE THREAD

**Issue by jamescassell** [coreos/fedora-coreos-tracker#371]
Adding fcct to the initrd would allow folks to pass their .fcc file directly on boot instead of having an extra manual step of compiling it.  Currently, this would add 9.4M to the initrd.

> 11:43 <cyberpear> James Cassell for "big changes", could we add fcct to the initrd so folks can just pass a .fcc rather than an .ign (and skip the intermediate step for the user)?  IIRC, it's
> 11:43 <bgilbert> bgilbert the original idea was that the Bodhi activation point represented a certain level of stability.  I don't think the exact landmark matters too much though
> 11:44 <dustymabe> Dusty Mabe cyberpear: you know that is a question I got asked a lot at the lab we did at devconf
> 11:44 at least 3 or 4 people raised their hand and asked me why the extra step was needed
> 11:44 <cyberpear> James Cassell the binary keeps growing, though... currently at 9.3M
> 11:45 <dustymabe> Dusty Mabe there are some reasons, but I think it's worth considering just including fcct in the initramfs and processing it into ignition before passing it to ignition
> 11:45 <bgilbert> bgilbert I'd like to see us try education first before giving up on the separate step
> 11:45 <cyberpear> James Cassell but I think the convenience tradeoff is probably worth it
> 11:45 <bgilbert> bgilbert offline validation does provide a lot of value, and we haven't given the ecosystem a lot of time to adapt yet
> 11:45 <cyberpear> James Cassell (assuming that fcc is the canonical spec folks should target)
> 11:46 <dustymabe> Dusty Mabe bgilbert: yeah, I see both sides
> 11:46 coming from a cloud-init world, it definitely seems awkward though
> 11:47 <dustymabe> Dusty Mabe I can't remember if there is already an issue for this or not
> 11:47 <bgilbert> dustymabe: yeah.  but we're trying to change the world, not become it :-)
> 11:47 <dustymabe> Dusty Mabe cyberpear: would you create one if there isn't one already
> 11:47 <cyberpear> James Cassell will do
> 11:47 <kaeso[m]> @kaeso:matrix.org (fwiw, I'm strongly against fcct in the initramfs)

**Comment by dustymabe** [comment]
Thanks for opening this. It does represent a gap in user expectations to pre-process one data format (FCC: human readable yaml with convenience factors) into a machine readable format (ignition, json) as a seprate step for the user. At least 3 or 4 users at the devconf.cz lab raised their hands to ask why we were converting from yaml to json by hand before sending the config to the machine for first boot. 

There are a few points of interest here:

- we aren't striclty converting from yaml to json (fcct is smarter than that and we are in the process of adding more convenience "sugar")
    - ignition is meant to be mostly distro agnostic, while fcct is meant to be more focused on implementing things that are specific to the OS
        - for example arch could choose systemd-networkd where FCOS could choose NM and fcct could implement a `network:` section that wrote out NM keyfiles and archct could implement a `network:` section that wrote out systemd-networkd configuration files
- fcct is validating the ignition config
    - having this as a separate step means the user can easily identify issues with their configs.
    - debugging errors in the initramfs is hard (console access, badly formatted terminal output, scrolling terminal output)

Even with these points above I think it is awkward for anyone coming from a `cloud-init` world to do this pre-process step so we should evaluate the options here and vote. I know CL didn't do this because CT configs weren't versioned, but FCCT configs are versioned so we have at least moved past that barrier.

**Comment by bgilbert** [comment]
I don't think voting is the best way to solve technical problems. :slightly_smiling_face:

As I mentioned in the transcript above (attribution seems to be missing for some reason) I think this a long-term education and tooling problem.  The premise is that it's better to do offline generation and validation rather than handcrafting a config and throwing it at a machine.  For that to work well, we need good offline tooling, including 1) graphical configurators and 2) transpilation built into provisioning services such as Matchbox.  We haven't given the ecosystem time to build out that tooling.  If we put FCCT in the initramfs, we remove the incentive for that to happen, and the opportunity for folks to discover the benefits of this model.

It's possible that the ecosystem won't accept the separate transpilation step, and we end up having to put FCCT in the initramfs after all.  But I think we should leave the friction in place for a couple years and see what the ecosystem comes up with.

**Comment by lucab** [comment]
> I know CL didn't do this because CT configs weren't versioned, but FCCT configs are versioned so we have at least moved past that barrier

I don't think this is the actual rationale for Container Linux, and I don't think it is a key point for FCOS either.

To the best of my understanding, for CL we took the Ignition route in order to settle on a configuration flow which was 1) machine-friendly 2) well-specified 3) easy to transpile to. This plugs into @bgilbert "offline generation" point.

I'm quite strongly against putting `fcct` into the initramfs because it undoes all of the above, plus it introduces yet another configuration flow based on smart auto-detection.

As a counterpoint, in the medium term I would expect most higher-level flows to be based on tools that are **NOT** `fcct`, but which directly emit Ignition configs. For example, [terraform](https://www.terraform.io/) is a very popular choice and it transpiles to Ignition.

**Comment by jamescassell** [comment]
>  (attribution seems to be missing for some reason)

Sorry, I fixed it.  GH markdown interprets the bracket-username-bracket as an HTML sequence and it gets hidden. (The others had an IRC "Real Name" specified, which didn't get hidden.)

**Comment by lucab** [comment]
Similar discussion on `matchbox` side regarding when/where transpiling should be happen: https://github.com/poseidon/matchbox/issues/786#issuecomment-587132334

**Comment by cgwalters** [comment]
> I'm quite strongly against putting fcct into the initramfs because it undoes all of the above, plus it introduces yet another configuration flow based on smart auto-detection.

Agreed.  Closing this; the other fix here is we need to [ship CLI tools](https://github.com/coreos/fedora-coreos-tracker/issues/235) - specifically a "test this fcct config with qemu" would be extremely useful - and the fcct :arrow_right: ignition would happen in that tool (per https://github.com/coreos/coreos-assembler/pull/670 ) and not in the host.

**Comment by dustymabe** [comment]
I'm definitely not agreed. I think this warrants more discussion in the future.

**Comment by cgwalters** [comment]
> I'm definitely not agreed. I think this warrants more discussion in the future.

Feel free to reopen?  But I think that'd be best if you have a particular new argument why fcct should be part of the initrd; if it's more "we should talk about how to better handle fcct/ignition for CoreOS users" that seems more of a vague thing that would be better in a separate ticket.
