### ISSUE TITLE
Documentation fix - install from ISO

### ISSUE THREAD

**Issue by shivarammysore** [coreos/fedora-coreos-tracker#403]
In https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/, command

```
curl -LO http://example.com/example.ign
```
does not work as certificate check will fail.  The correct command should be:

```
curl  -k -LO http://example.com/example.ign
```

**Comment by bgilbert** [comment]
If taken literally, of course, the example works fine because we're fetching from `example.com` over HTTP.

I don't think we want to encourage users to ignore certificate checks by default.  If you know you're fetching from an internal server with an invalid certificate, (a) please consider fixing your server to have a valid certificate, and (b) you can add the `-k` option yourself.

**Comment by shivarammysore** [comment]
@bgilbert you are right in your comment, but if there is a http and https server and only the http side is serving this  file, then there is a automatic redirect to https and it can cause issues - even for self signed cert - at least in my limited testing.

**Comment by bgilbert** [comment]
The actual `example.com` supports both HTTP and HTTPS.  I tried

```
curl -v -LO http://example.com/example.ign
```

and it correctly fetched over HTTP.

**Comment by lucab** [comment]
I agree with @bgilbert and I'm inclined to close this ticket. In particular this part:

> then there is a automatic redirect to https and it can cause issues - even for self signed cert - at least in my limited testing

Following from https://github.com/coreos/fedora-coreos-tracker/issues/402#issuecomment-593327923, likely this is specific to @shivarammysore's setup which:
 * redirects HTTP to HTTPS
 * uses a self-signed (i.e. untrusted) certificate for HTTPS

**Comment by shivarammysore** [comment]
Ok - will close the ticket.  Thanks
