### ISSUE TITLE
System keeps restarting after installation 

### ISSUE THREAD

**Issue by hrkut** [coreos/fedora-coreos-tracker#471]
After installation of version 31.20200407.3.0 stable to the Dell PowerEdge R340 the system keeps restarting after first boot. Please see the attached picture.

![rpviewer-4](https://user-images.githubusercontent.com/1424587/80746421-25599c00-8b22-11ea-9d9c-b0caa92439b2.png)

**Comment by dustymabe** [comment]
hey @hrkut - Unfortunately we'll probably need some more information in order to diagnose the problem. It would help if we could get more logs (either a recorded video session or use a serial console). It would also help if you describe exactly how you performed the install.

**Comment by hrkut** [comment]
It was a regular installation using ISO image and iDrac console (Dell tools). I followed instruction on https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/. I created an ign file and use coreos-install. System was installed fine, but after sudo reboot, it keeps restarting. I can't start the system, so I can't provide any log.

**Comment by dustymabe** [comment]
Since you are using an iDrac can you record a screencast of the install/firstboot? We really can't do much without more information.

**Comment by hrkut** [comment]
Here you are. A real-time uncut screencast (30 minutes):
https://www.dropbox.com/s/ie5am1e5xgmfau7/2020-05-01-11-40-10.avi?dl=0

**Comment by dustymabe** [comment]
hey @hrkut 

It turns out your Ignition config is for the wrong version of Ignition.

![ignition-fetch-fail](https://user-images.githubusercontent.com/4530030/80810942-e283dc80-8b92-11ea-9fee-c4dc6b19cb04.png)

![ignition](https://user-images.githubusercontent.com/4530030/80810949-e57ecd00-8b92-11ea-9f73-0061b50071c5.png)

We recommend you use the `fcct` tool to generate Ignition configs (as it will validate the config for you), but if you insist on creating or generating your own Ignition configs we do provide a tool called `ignition-validate` as part of our Ignition releases that you can use to validate the config as well. On Fedora you can `dnf install ignition-validate` or you can grab the binary from the latest Ignition release: https://github.com/coreos/ignition/releases/tag/v2.2.1

**Comment by dustymabe** [comment]
All that being said, IIUC the system shouldn't boot loop. I'll have to see if I can reproduce that locally.

**Comment by dustymabe** [comment]
OK I know what's happening. In my local reproduction (over a serial console) I see:

```
Press Enter for emergency shell or wait 4 minutes 45 seconds for reboot.

Generating "/run/initramfs/rdsosreport.txt"


Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot
after mounting them and attach it to a bug report.


Press Enter for maintenance
(or press Control-D to continue):
```


I think the problem is that the emergency console only goes to ttyS0 (which is the default primary console of the machine) and you are on tty0. 

This means you never see the `Press Enter for emergency shell or wait 4 minutes 45 seconds for reboot.`, so after 5 minutes it does indeed timeout and fail again.

**Comment by hrkut** [comment]
Thank you very much, that was the reason. I created the ign file using tools from CoreOS. Now it works ok. And using iDrac remotely I didn't have access the ttyS0 console. It would by nice have a message about problems with ign file in the tty0 console as well.

**Comment by dustymabe** [comment]
Glad that you got it working! The error messages I screen captured from your screen recording did come to the tty0 console, but the emergency bash prompt didn't. There might be some way we can make the emergency shell go to more consoles than just the primary one, but we'd need to investigate that. For now I'm going to close out this issue.
