### ISSUE TITLE
Container Linux migration tools

### ISSUE THREAD

**Issue by dm0-** [coreos/fedora-coreos-tracker#48]
The Container Linux distro currently has a planned EOL in 2020, and users will need to migrate to Fedora CoreOS to remain supported.  We'll need to decide on what tooling can be built to automate parts of the transition, and document the differences to make the migration is as painless as possible.

**Comment by ajeddeloh** [comment]
Tools we will need:
 * **Ignition 2.x -> 3.0.0 "best effort" translator**: Perfect translation between Ignition spec 2.x and 3.0.0 is not possible for all cases, but we can get 95% of the way there. At bare minimum we'll want a tool that does a mechanical translation and ignores [weird edge cases](https://github.com/coreos/ignition/issues/608). We may also want it to try to detect differences between the OSs it targets and make recommendations (e.g. path `x/y/z` on CL is `a/b/c` on FCOS, consider changing that) or that automatically makes those changes.
 * **CLC -> FCOSC "best effort" translator**: Similar to how perfect translation for Ignition is not possible, perfect translation for CLCs is not possible. However we can do better than with Ignition since the higher level sugar can stay the same between OSs (just will result in different Ignition configs). 

Things we should _not_ build:
* CLC -> Ignition 3.0.0 tool. Use the CLC->FCOSC tool then FCOSCT to generate Ignition 3.0.0.

**Comment by ajeddeloh** [comment]
I'm less inclined to support that because:
1) Cloud configs tend to have hacks to work around the limitations of coreos-cloudinit. This means we wouldn't be able to do as good a job.
2) It'd be somewhat of an attractive nuisance to upstream cloudinit users

**Comment by bgilbert** [comment]
FWIW, the [FAQ](https://coreos.fedoraproject.org/blogs/faq.html) apparently says that we'll provide "tooling to help convert existing cloud-configs and Ignition configs for use on Fedora CoreOS".

**Comment by ajeddeloh** [comment]
That's... less than ideal, but I still think we ought to not. At most just build a tool that knows how to translate very specific sections and fail/not convert others. The CLC->FCOSC and Ignition 2.x->3.0.0 converters are much higher priority imo.

**Comment by bgilbert** [comment]
Spinning out the docs portion to #159 so this issue can focus on tooling.

**Comment by bgilbert** [comment]
Closing as moot.
