### ISSUE TITLE
Fedora Test day for our `next` stream (Fedora 32)

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#491]
The Fedora QA team has reached out to me many times to try to organize a test day. We're finally to the point where we can appropriately hold a test day for the next big thing to come to Fedora CoreOS. I met with @kparal and @sumantro93 today to discuss what we want our Fedora 32 test day to look like. 

I will note early on here that Fedora CoreOS has automated testing that covers many of the test cases that we would run on a test day. However ther is still value in running a test day. They are the following:

- raise awareness of FCOS
- catch issues with documentation,
- catch issues with user experience
- catch bugs not covered in automation/CI

This means our test day will probably be a little more loosely defined than other edition's test days, but that's OK. We've [started a hackmd](https://hackmd.io/lX41BH4TSlqDGqgwr_xWVg?view) to brainstorm test cases we can try to have people to run. Please add ideas to the notes in the hackmd.

Some time next week kamil and sumatro and I will sync (maybe at the community meeting on wednesday) on the notes in the hackmd and choose a day for the test day on the following week. The Fedora QA team will then spend some time formalizing the flow for the test day (wiki pages, blog posts, etc) and we'll have the test day.

xref: [Fedora QA ticket](https://pagure.io/fedora-qa/issue/616)

**Comment by dustymabe** [comment]
An idea that was floated in our discussion earlier with kamil and sumantro was that we might be able to use the test day as an "office hours" day for people migrating from CL to come ask questions and get help with that as well. @bgilbert @lucab @arithx - Does that sound like something that we'd like to do?

**Comment by shivarammysore** [comment]
You may want to consider adding - upgrade and downgrade scenarios to the list of install tests.

**Comment by dustymabe** [comment]
Thanks @shivarammysore! The hack md doc is open to suggestions (you can edit it). Would you like to add those suggestions? https://hackmd.io/lX41BH4TSlqDGqgwr_xWVg?view ?

**Comment by lucab** [comment]
@dustymabe happy to answer stuff, to the best of my knowledge. Is that on IRC? I usually watch that anyway during EU times.

**Comment by kparal** [comment]
>  Is that on IRC?

Yes. We usually keep it on `#fedora-test-day`, but in this case, it might be better to use `#fedora-coreos`, if you prefer.

**Comment by shivarammysore** [comment]
@dustymabe Done - https://hackmd.io/lX41BH4TSlqDGqgwr_xWVg?view#Upgrades-amp-Downgrades

**Comment by lucab** [comment]
During last meeting, we tentatively scheduled TestDay on June 8th (hoping this also fits into @dustymabe plans).

Till then, let's keep adding notes and ideas to the hackmd doc.

**Comment by dustymabe** [comment]
> During last meeting, we tentatively scheduled TestDay on June 8th (hoping this also fits into @dustymabe plans).

👍 - I have no issues with that plan

**Comment by sumantro93** [comment]
@lucab @dustymabe did you guys get time to take a look at the Test Cases? 
All of them are http://testdays.fedorainfracloud.org/events/84
Please gives us feedback or help us editing them directly. 
@kparal , coremodule and @sumantrom will be around in today's meeting if you have anything specific to say

**Comment by dustymabe** [comment]
We discussed this during the [meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/AVZYYTOXQCLSM5WTERTBR2C7MQ2JTMHG/).

We agreed to have the test day on 06/08. @jlebon and I will review the test cases and help update them if anything needs to be changed. Here is the test mailing list announcement about the test day with more info: https://lists.fedoraproject.org/archives/list/test@lists.fedoraproject.org/thread/HL4BSOGIAH6AB5H7KW3IOKOB4MBE7V5N/

**Comment by kparal** [comment]
Here's another public announcement:
https://communityblog.fedoraproject.org/contribute-at-the-fedora-coreos-test-day/

**Comment by kparal** [comment]
The testcases are now in a proper location and the testday app has been updated. Everything should be ready for Monday.
http://testdays.fedorainfracloud.org/events/84

**Comment by shivarammysore** [comment]
I added a standard YAML file for Ignition so that it can be used to test
all the scenarios.  This can be a great place to start the final system
smoke test so that there is no DOA.

https://hackmd.io/lX41BH4TSlqDGqgwr_xWVg?view

Thanks

**Comment by kparal** [comment]
> I added a standard YAML file for Ignition so that it can be used to test all the scenarios. This can be a great place to start the final system smoke test so that there is no DOA. https://hackmd.io/lX41BH4TSlqDGqgwr_xWVg?view Thanks

I can upload it to the wiki and reference it in all test cases. Note that most people then might use the prepared fcct config instead of going through documentation and write their own, so it depends what your goal is. Another way is to show just snippets of the config to perform that particular testcase. Or prepare full configs, but with just relevant sections for the test case. They can be stored on wiki or e.g. managed in your team gist.

I wonder if it's a good idea to teach people to run docker as root without a password, and set up aliases for both docker and podman this way? It doesn't sound like something that should be present in an example config file.

Also, is there a way to make those file contents readable and not base64-encoded? It's obscure for people when they don't know what they are configuring their system with. Why is the specified charset iso-8859-7 and not utf-8?

I decided to hold off on test case customization before we clarify this, I wasn't sure whether I should use the config file as it is. But if you think it's fine, please feel free to edit the test cases and link to the config file as an example. Or tell me, thanks.

**Comment by dustymabe** [comment]
@kparal - I think we should probably not add that specific config to the test cases. It's a good example of an exploratory test case where a user applies their own custom config, but I don't think it should be used generically. It's a good reference for other users who want to build their own, though. Thanks @shivarammysore for posting it!

**Comment by shivarammysore** [comment]
@dustymabe - you are right in saying that not everything in that is to be
used directly.  I use it personally as I have been unable to move all of my
infrastructure to `podman` due to certain requirements.
@kparal - charset `iso-8859-7` has worked for me.  `utf-8` could also
possibly work but not tested.  You could include one more file with `utf-8`
and see if it passes the test.

**Comment by kparal** [comment]
Hey folks, the test day is over now. I learnt that the testday app went down in the during the US workday and we only fixed it today. I'm really sorry for that, it was an unlucky coincidence related to the Fedora Infra move (that's why we run it on a private instance temporarily, which got overloaded). So while the attendance looks decent, it was probably better than it seems, US-based folks just didn't submit results :-/ Hopefully they'll re-submit them today.

Do you have any feedback on the test day itself? Did it pass your expectations? Did you receive any good feedback or bug reports? Would you like to change something in a future test day? Thanks!

https://fedoraproject.org/wiki/Test_Day:Fedora_32_CoreOS_2020-06-08
http://testdays.fedorainfracloud.org/events/84 (the results will get exported to the wiki for archival purposes in a few weeks)

**Comment by sumantro93** [comment]
> Hey folks, the test day is over now. I learnt that the testday app went down in the during the US workday and we only fixed it today. I'm really sorry for that, it was an unlucky coincidence related to the Fedora Infra move (that's why we run it on a private instance temporarily, which got overloaded). So while the attendance looks decent, it was probably better than it seems, US-based folks just didn't submit results :-/ Hopefully they'll re-submit them today.
> 
> Do you have any feedback on the test day itself? Did it pass your expectations? Did you receive any good feedback or bug reports? Would you like to change something in a future test day? Thanks!
> 
> https://fedoraproject.org/wiki/Test_Day:Fedora_32_CoreOS_2020-06-08
> http://testdays.fedorainfracloud.org/events/84 (the results will get exported to the wiki for archival purposes in a few weeks)

I would like to have the feedback on this test day. I have transferred the results back to the wiki. Thanks a lot to all of you folks for the help!

**Comment by dustymabe** [comment]
hi @sumantro93 @kparal. I believe the test day was very valuable. We had quite the turnout from the community and also it gave me and a few others who work on FCOS daily to try out some new things. From the test day we found quite a few documentation fixups we want to make. Some of them have already been PRd and some are in progress. We also found a few bugs that we wanted fixed and we released an intermediate `testing` release to fix the bug before Fedora 32 landed in our `stable` stream.

Overall I think it's the most successful test day I've ever had part in organizing. Thank you so much for helping us with this and we look forward to working with the QA team in the future.

**Comment by lucab** [comment]
For reference, these are the tickets we collected from TestDays: https://github.com/coreos/fedora-coreos-tracker/issues?q=is%3Aissue+label%3Afedora-test-day+.

**Comment by kparal** [comment]
Great, nice to hear. We'll be of course happy to repeat this for F33 FCOS. But even if you have some feature or a change that you want to test sooner than that, feel free to ping us or create a ticket and we'll be happy to set it up for you:
https://fedoraproject.org/wiki/QA/Test_Days

**Comment by dustymabe** [comment]
Thanks! Closing this now.
