### ISSUE TITLE
Support setting kernel args for the installed OS image

### ISSUE THREAD

**Issue by abhinavdahiya** [coreos/fedora-coreos-tracker#533]
When PXE booting FCOS/RHCOS the coreos-installer provides options to install OS image and the Ignition config that should be used to configure on the reboot.

There are cases where users might want to provide kernel args for the OS image that is installed by coreos-installer.

An example is:

the FCOS OS image by default has `console=ttyS0,115200n8` as the kernel parameter. But when you try to PXE boot FCOS in Packet.net `console=ttyS1,115200n8` is required to get output on the [SOS console](https://support.packet.com/kb/articles/sos-serial-over-ssh)

also an Ignition config that needs to fetch extra configuration from network, `rd.neednet=1` is required so that Ignition has DHCP/network available in initramfs.

**Comment by jlebon** [comment]
OK, opened https://github.com/coreos/coreos-installer/pull/268. With this one can do e.g.

```
$ coreos-installer install --persistent-args 'console=ttyS1,115200n8' /dev/sda
```

(There is still the question of whether we want to auto-forward the console argument so users don't have to specify it. It's really tempting...)

**Comment by brokenjacobs** [comment]
that will only work if the console=ttyS0,115200n8 arg is removed from the default. Otherwise you get no console.

Another point I would like to bring up here is that sometimes kernel arguments are needed on hardware platforms to get them to boot at all. Back on CoreOS we had a raid card that would only work if we disabled the intel iommu with a kernel argument, otherwise you couldn't install or boot the system. Not being able to set the arguments from the moment the kernel loads after install (at least optionally) will break some hardware platforms.

For my use case, being able to completely specify the kernel arguments in the ignition would work just fine, so long as the console=ttyS0,115200n8 is removed from the default arguments.

**Comment by dustymabe** [comment]
> that will only work if the console=ttyS0,115200n8 arg is removed from the default. Otherwise you get no console.

The last entry will be the primary console, right? My understanding is that if you had `console=tty0 console=ttyS0,115200n8 console=ttyS1,115200n8` all on the command line the primary console would be the last entry (`console=ttyS1,115200n8`).


> Another point I would like to bring up here is that sometimes kernel arguments are needed on hardware platforms to get them to boot at all. Back on CoreOS we had a raid card that would only work if we disabled the intel iommu with a kernel argument, otherwise you couldn't install or boot the system. Not being able to set the arguments from the moment the kernel loads after install (at least optionally) will break some hardware platforms.

I think @jlebon addresses this in https://github.com/coreos/fedora-coreos-tracker/issues/533#issuecomment-642234015 and it's why he opened https://github.com/coreos/coreos-installer/pull/268 so that users can add kargs persistently via the installer. Does that not address this need?

> For my use case, being able to completely specify the kernel arguments in the ignition would work just fine, so long as the console=ttyS0,115200n8 is removed from the default arguments.

Yeah I think we would definitely need some way to "remove" existing arguments with "kargs-via-Ignition". It might even be beneficial to add the ability to remove args via the `coreos-installer install --persistent-kargs` approach as well. Maybe starting a karg with `-` could mean we want it removed, though that may make parsing the CLI options for `coreos-installer` harder.

**Comment by brokenjacobs** [comment]
In our testing the first argument is becomes the serial console, not the last. Which means no console on the first reboot, but it comes back after manipulating args with rpm-ostree and rebooting.

**Comment by dustymabe** [comment]
> In our testing the first argument becomes the serial console, not the last.

May I ask what you are testing? Are you testing the un-merged code in https://github.com/coreos/coreos-installer/pull/268 ?

**Comment by brokenjacobs** [comment]
No. We are using coreos stable appending kernel args with the installer. The kernel ends up with two serial console arguments

**Comment by jlebon** [comment]
> In our testing the first argument becomes the serial console, not the last.

Ahh yup, good catch. I think we were under the assumption that the last `console=` wins. But it's a little more nuanced than that. Reading from [the docs](https://www.kernel.org/doc/html/latest/admin-guide/serial-console.html) and testing, between `console=` arguments of *different* types, the last one wins for who gets control of `/dev/console`, but within the set of console arguments for the *same* type, the *first* one wins (not just for control of `/dev/console`, but any output at all).

>> For my use case, being able to completely specify the kernel arguments in the ignition would work just fine, so long as the console=ttyS0,115200n8 is removed from the default arguments.
>
> Yeah I think we would definitely need some way to "remove" existing arguments with "kargs-via-Ignition". It might even be beneficial to add the ability to remove args via the coreos-installer install --persistent-kargs approach as well.

Yeah... I wanted to avoid supporting this until the need came up (and ideally just leave the more complex operations to the kargs-via-Ignition path). `--persistent-args` as implemented in https://github.com/coreos/coreos-installer/pull/268 also is nicely symmetrical with `--firstboot-args`.

But given that setting `console` args is one of the primary arguments for doing this, I'll change https://github.com/coreos/coreos-installer/pull/268 to support this. (And in the end it also helps with point (1) of https://github.com/coreos/fedora-coreos-tracker/issues/533#issuecomment-642234015).

**Comment by dustymabe** [comment]
This made it into coreos-installer [v0.3.0](https://github.com/coreos/coreos-installer/releases/tag/v0.3.0).

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `32.20200726.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `32.20200726.3.1`.
