### ISSUE TITLE
ostree 2020.4 breaks live image

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#589]
Booting a Fedora CoreOS live PXE image with ostree 2020.4, `ostree-prepare-root` says:

```
[   18.764271] systemd[1]: Starting OSTree Prepare OS/...
[   18.775260] ostree-prepare-root[557]: Resolved OSTree target to: /sysroot/ostree/deploy/fedora-coreos/deploy/09709ed011683ed162a7664f21d3f356066e321ecf1861031e15deec6068646d.0
[   18.778340] ostree-prepare-root[557]: ostree-prepare-root: sysroot=readonly currently requires writable / in initramfs
```

`/sysroot` is a squashfs, so it's read-only, of course.  This check was introduced by https://github.com/ostreedev/ostree/pull/2113, which doesn't make it clear _why_ `/sysroot` needs to be rw.

**Comment by cgwalters** [comment]
What ostree and the live ISO are doing strongly overlap here; it would be good if we could dedup them.

The rationale behind this check is because `/etc` needs to be writable.  If we just removed it we'd end up with two `/etc` mounts (which might work or might not, but if it did it'd be ugly).

I think to rationalize this we'd need to teach ostree to understand the liveiso case of "make /etc non-persistent in a tmpfs" - the current ostree code is assuming you have `/etc` on `/`.

**Comment by cgwalters** [comment]
Working on a patch.

**Comment by cgwalters** [comment]
https://github.com/coreos/coreos-assembler/pull/1633

**Comment by jlebon** [comment]
This is fixed now!

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-config/pull/541
https://github.com/coreos/fedora-coreos-config/pull/542
