### ISSUE TITLE
How to create Live  ISO image?

### ISSUE THREAD

**Issue by zhouji3x** [coreos/fedora-coreos-tracker#621]
I built CoreOS from source,   the output,  build/images/amd64-usr/latest/coreos_production_image.bin, is not bootable.
I tried creating ISO by using script image_to_vm.sh,  the ISO file is not bootable too.

How to create Live  ISO image like  https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/32.20200824.3.0/x86_64/fedora-coreos-32.20200824.3.0-live.x86_64.iso?

Thanks

**Comment by lucab** [comment]
It looks like the problem is that you are following instructions for Container Linux.
Instead, Fedora CoreOS is built via https://github.com/coreos/coreos-assembler.

Please note that the coreos-assembler is not meant to be a user-facing component, we discourage building custom versions of FCOS and we don't provide support for that kind of flow. It may or may not work in your environment.
