### ISSUE TITLE
Networking failure if is set bond

### ISSUE THREAD

**Issue by kr45sty** [coreos/fedora-coreos-tracker#715]
**Describe the bug**
I have some problem with networking if i set bond. After clear instalation sometime networking works sometimes not.
In journal logs i found some errors about buffer space which relates with this problem. I tried increase sysctl net.ipv4.tcp_*mem parameters but without any results.

The same bond configuration works on Debian.

**Reproduction steps**
1. Set bond in ignition
2. Install Fedora CoreOS 33.20201214.3.1
3. Reboot

**System details**
 - Bare Metal (ProLiant m710x Server Cartridge, Mellanox ConnectX3Pro 2.42.5600)
 - Fedora CoreOS 33.20201214.3.1

**Ignition config**
```
variant: fcos
version: 1.0.0
storage:
  files:
    - path: /etc/NetworkManager/system-connections/bond0.nmconnection
      mode: 0600
      overwrite: true
      contents:
        inline: |
          [connection]
          id=bond0
          type=bond
          interface-name=bond0

          [bond]
          downdelay=0
          miimon=100
          mode=802.3ad
          updelay=0

          [ipv4]
          address1=X.X.104.4/24,X.X.104.1
          dns=8.8.8.8;
          method=manual
    - path: /etc/NetworkManager/system-connections/eno1.nmconnection
      mode: 0600
      overwrite: true
      contents:
        inline: |
          [connection]
          id=eno1
          type=ethernet
          interface-name=eno1
          master=bond0
          slave-type=bond
    - path: /etc/NetworkManager/system-connections/eno1d1.nmconnection
      mode: 0600
      overwrite: true
      contents:
        inline: |
          [connection]
          id=eno1d1
          type=ethernet
          interface-name=eno1d1
          master=bond0
          slave-type=bond
```
 
**Additional information**
```
NetworkManager[38224]: <warn>  [1610624466.9999] ndisc[0x55d2ca4780f0,"bond0"]: failure sending router solicitation: No buffer space available (105)
NetworkManager[38224]: <debug> [1610624470.7576] ndisc[0x55d2ca4780f0,"bond0"]: failure sending router solicitation: No buffer space available (105)
```

Sometimes
`<error> [1610617888.3849] platform-linux: sysctl: failed to set 'bonding/ad_actor_system' to '00:00:00:00:00:00': (22) Invalid argument`

**Comment by jlebon** [comment]
Hmm, not sure what's going on there. @thom311 Any ideas?

**Comment by huitee** [comment]
Whether the issue has been solved ?

**Comment by thom311** [comment]
sorry for the late reply.

> <error> [1610617888.3849] platform-linux: sysctl: failed to set 'bonding/ad_actor_system' to '00:00:00:00:00:00': (22) Invalid argument

This error is harmless. See [here](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/commit/9e7af314546d7912ee23b3850230008902aca4d3) and [here](https://bugzilla.redhat.com/show_bug.cgi?id=1931881).

> NetworkManager[38224]: <warn>  [1610624466.9999] ndisc[0x55d2ca4780f0,"bond0"]: failure sending router solicitation: No buffer space available (105)

OK, that's unusual. I don't remember seeing this. It most likely means that `sentto()` failed with `ENOBUFS`. It alone might not be a problem however, because the neighbor discovery algorithm can afford that a router solicitation is lost. It should recover from that and retry. Of course, it might hint to a larger problem...

---

Please always provide complete logs. The snippets provided are not conclusive and the failure description is not very clear. Usually [this](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/main/contrib/fedora/rpm/NetworkManager.conf#L27) explains how to collect debug logs with NetworkManager. In this case however, you probably need to set `rd.debug` on the kernel command line (as this happens in initrd, I presume?).

**Comment by dustymabe** [comment]
@kr45sty - are you still having this issue?

**Comment by kr45sty** [comment]
> @kr45sty - are you still having this issue?

No, i no longer use CoreOS. I'm using Debian and there is no problem with it.
Thanks.
