### ISSUE TITLE
Unclear/undocumented how to force upgrade FCOS distro

### ISSUE THREAD

**Issue by ppettina** [coreos/fedora-coreos-tracker#851]
**Describe the bug**
The latest upgrade of FCOS (based on Fedora 34) broke binary compatibility of some utilities we had installed (I know we should have used docker containers). We rebuilt the utilities, however they failed on nodes that had not yet updated to the newer version. We tried to update them manually with combination of the following commands but all failed:

```
rpm-ostree cleanup -p
rpm-ostree upgrade -r
rpm-ostree deploy revision=b4b2199ec09b9e4200024b52062b119035a06b3ffc27b4268c5b8c3aa6fcde17 -r
```

Presumably there's a way to do this using Zincati, however it is not documented (or my googling was insufficient). Regardless of the reason, I presume forcing an update to the latest version should be an option?

Possibly an easy one for @lucab ?

**Reproduction steps**
N/A 

**Expected behavior**
There should be a well-documented way to upgrade FCOS to the latest available version in a stream.

**Actual behavior**
There is no documented way to upgrade FCOS to the latest available version in a stream.

**System details**
N/A

**Ignition config**
N/A

**Additional information**
N/A

**Comment by lucab** [comment]
Thanks for the report. I think you are omitting too many details to understand what you are trying to do, but I'll answer to the best of my understanding.

Generally speaking, in the default configuration FCOS nodes do upgrade as soon as they see that there is an update available.
If a node is not updating (when? from which version? to which version? on which channel?) its Zincati metrics and logs will tell the reason.
It could be due to custom configurations (any here?), or because of some errors, or even simply because there are no updates available for *that specific node*.

Aside, you can also stop Zincati and perform some manual `rpm-ostree` operations like you did above (possibly causing more troubles to the node). If they failed (with which errors?), it's a probably a symptom that something is messed up in the overall OS setup.

In all the cases above "force upgrade through Zincati" won't be able to solve the deeper issues, and does not exist as a catch-all action. You can nudge the agent to react [even more eagerly](https://docs.fedoraproject.org/en-US/fedora-coreos/auto-updates/#_wariness_to_updates) to possible updates, but I don't think that's what you are facing here.

**Comment by ppettina** [comment]
Right, I think Zincati might have been preventing the update from completing.
As you say, I might have omitted too much...
```

$ cat /etc/zincati/config.d/55-updates-strategy.toml
[updates]
strategy = "periodic"

[[updates.periodic.window]]
days = [ "Sat", "Sun" ]
start_time = "06:30"
length_minutes = 60
```
So after stopping & disabling zincati, and rebooting, this worked:
```
sudo rpm-ostree deploy revision=b4b2199ec09b9e4200024b52062b119035a06b3ffc27b4268c5b8c3aa6fcde17 -r
```
(that's the hash of the current FCOS 34 release)

Logs from Zincati don't say much:
```
$ journalctl -u zincati
Failed to execute 'pager', using next fallback pager: Permission denied
-- Journal begins at Tue 2021-05-04 14:07:25 UTC, ends at Tue 2021-06-01 10:36:35 UTC. --
Jun 01 09:07:48 build-worker-large-fcos-4 systemd[1]: Stopping Zincati Update Agent...
Jun 01 09:07:48 build-worker-large-fcos-4 systemd[1]: zincati.service: Succeeded.
Jun 01 09:07:48 build-worker-large-fcos-4 systemd[1]: Stopped Zincati Update Agent.
-- Boot a3e7535025a04b53bdff7f51465bc6ce --
Jun 01 09:11:51 build-worker-large-fcos-4 systemd[1]: Started Zincati Update Agent.
Jun 01 09:11:51 build-worker-large-fcos-4 zincati[1480]: [INFO ] starting update agent (zincati 0.0.14)
Jun 01 09:11:59 build-worker-large-fcos-4 zincati[1480]: [INFO ] Cincinnati service: https://updates.coreos.fedoraproject.org
Jun 01 09:11:59 build-worker-large-fcos-4 zincati[1480]: [INFO ] agent running on node '29074157dc51473bba54853b63e4cd92', in update group 'default'
Jun 01 09:11:59 build-worker-large-fcos-4 zincati[1480]: [INFO ] initialization complete, auto-updates logic enabled
Jun 01 09:12:00 build-worker-large-fcos-4 zincati[1480]: [INFO ] current release detected as not a dead-end
Jun 01 09:12:01 build-worker-large-fcos-4 zincati[1480]: [INFO ] target release '34.20210427.3.0' selected, proceeding to stage it
Jun 01 09:29:41 build-worker-large-fcos-4 systemd[1]: Stopping Zincati Update Agent...
Jun 01 09:29:41 build-worker-large-fcos-4 systemd[1]: zincati.service: Succeeded.
Jun 01 09:29:41 build-worker-large-fcos-4 systemd[1]: Stopped Zincati Update Agent.
... (repeat for each reboot) ...
```
---
So I presume the takeaway here is that Zincati might have prevented the update to complete because of the configuration? Where would this be logged?

**Comment by ppettina** [comment]
That doesn't tell the whole story however. This was the output of `rpm-ostree status` before the update:
```
$ sudo rpm-ostree status
State: idle
Deployments:
● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 33.20210104.3.0 (2021-01-18T11:30:26Z)
                    Commit: 085622ea1fbe723226fe09ddd7388d3d39e4b43ec6bb828b9a9aaa842a057287
              GPGSignature: Valid signature by 963A2BEB02009608FE67EA4249FD77499570FF31

  ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 33.20201214.3.1 (2021-01-05T00:05:03Z)
                    Commit: a64854cbcec13e1c3b3ccbfd3802e377e23c0c136d384c32736addf77e0e2a03
              GPGSignature: Valid signature by 963A2BEB02009608FE67EA4249FD77499570FF31
```

I had rolled back from 33.20201214.3.1 to 33.20210104.3.0 , however these are really old versions from January. Actually I had noticed a number of nodes stuck on this version (33.20201214.3.1) that didn't readily upgrade. What could cause FCOS to entirely skip 5 or more updates?

**Comment by lucab** [comment]
> So I presume the takeaway here is that Zincati might have prevented the update to complete because of the configuration?

It looks like so. Jun 01 is Tuesday. According to your configuration, the next window available for updates is Saturday (Jun 05) at 6:30.

> What could cause FCOS to entirely skip 5 or more updates?

Plenty of things, possibly some errors. Zincati metrics and logs from any of the nodes stuck should be able to tell you what's going on.

**Comment by ppettina** [comment]
Well I guess this situation is too vague to keep debugging - Zincati journal logs are inconclusive and I don't have other metrics. 

I realise there have been no Zincati logs on journalctl for about 4 months (logs on my nodes start in February but Zincati only has entries from the past 3 days and the last FCOS upgrade must have been in January).

Plus Zincati was running at version 0.0.14 and the currently deployed one is 0.0.19.

I have one more question before I close the issue - is there a CLI command or sequence of commands that can trigger an immediate update, without having to change the configuration (e.g. update weariness)?

**Comment by lucab** [comment]
I agree, without logs nor metrics it's very hard to draw any conclusion. From the last logs posted there was nothing obviously wrong, and upgrades should have eventually happened next Saturday.

> I have one more question before I close the issue - is there a CLI command or sequence of commands that can trigger an immediate update, without having to change the configuration (e.g. update weariness)?

Not in that form. But for your usecase it would have been enough to have a "temporarily ignore configured strategy" verb in order to immediately finalize the already staged upgrade.
This feature request has surfaced in different forms in other places, I've noted it down at https://github.com/coreos/fedora-coreos-tracker/issues/392#issuecomment-850417840, and it would be a good one to implement.

**Comment by ppettina** [comment]
So according to https://github.com/coreos/fedora-coreos-tracker/issues/392#issuecomment-850417840 ...
The following seems to work:
```
sudo tee /run/zincati/config.d/99-override.toml << EOF
[updates]
strategy = "immediate"
reboot = false
EOF

sudo systemctl restart zincati
```

from the logs:
```
zincati[24023]: [INFO ] update strategy: immediate
```
instead of (e.g.)
```
zincati[1054]: [INFO ] update strategy: periodic, total schedule length 120 minutes (next window in 10h 14m)
```


Downside is that if there is no update to do, the configuration remains in place until reboot.
