### ISSUE TITLE
Potential security vulnerability related to metadata.google.internal usage on GCP

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#885]
**Describe the bug**

The details are in https://github.com/irsl/gcp-dhcp-takeover-code-exec

This needs investigation to find out if Afterburn or Ignition are affected.

This is restricted to GCP only.

See also: https://gitlab.com/gitlab-com/gl-security/security-operations/gl-redteam/red-team-tech-notes/-/tree/master/oslogin-privesc-june-2020

**Comment by travier** [comment]
The README mentions:

> gain root access by getting SSH keys added by google_guest_agent

We don't ship `google_guest_agent` AFAIK but Afterburn could use the same mechanism.

**Comment by cgwalters** [comment]
I think the key to this attack is changing what `metadata.google.internal` means via DNS.  If instead we hardcode the link-local IP address (as e.g. we do for AWS), we shouldn't be vulnerable.

But indeed afterburn uses the hostname: https://github.com/coreos/afterburn/blob/9f5717e726e6b9ef22e66d8ea9c3eba5e1cee2a9/src/providers/gcp/mod.rs#L58

I suspect at some point Google will have an official response but hardcoding the IP address short term makes sense to me.

**Comment by bgilbert** [comment]
Ignition [also uses the hostname](https://github.com/coreos/ignition/blob/041b14248e62f3992674781cf3cb0dadb3a8e233/internal/providers/gcp/gcp.go#L34) to fetch userdata.

**Comment by darkmuggle** [comment]
The nature of the attack requires that a rouge DHCP/DNS server exist on the network -- something that is not new or unique to GCP. To effect this attach, the account first must be compromised, a new VM launched, and the then the take over-attempt happens. It's really no different than plugging a rouge computer in via an ethernet cable. 

Trying to defend against this sort of attack is going to be _really_ difficult without GCP.

**Comment by cgwalters** [comment]
cloud-init also uses the hostname; https://github.com/canonical/cloud-init/blob/fbcb224bc12495ba200ab107246349d802c5d8e6/cloudinit/sources/DataSourceGCE.py#L19

**Comment by cgwalters** [comment]
> The nature of the attack requires that a rouge DHCP/DNS server exist on the network -- something that is not new nor is the attack unique to GCP. 

Leaving all other differences between clouds aside (e.g. whether AWS allows DHCP packets to traverse subnets by default etc.) the claim here is that because of the use of a link-local IP address, a rogue DHCP server cannot cause the host to request metadata from something other than the trusted cloud hypervisor, which blocks this attack.  That's why it's unique to GCP.

> To effect this attach, the account first must be compromised, a new VM launched, 

No - if e.g. a running container in kube is compromised (webserver or whatever) and then the attacker leverages a LPE to gain uid 0 on a single host (but not cluster `kube:admin`) they could then leverage *this* in GCP to take over a control plane machine and etcd for example, or other hosts.  It doesn't require compromising the GCP account or spawning a new VM.

**Comment by bgilbert** [comment]
Also, the rogue DHCP packets don't have to come from the same network if the GCP firewall is turned off; see attack 3 in the writeup.

I think the writeup is saying that the attack depends on a dhclient exit hook (`google_set_hostname`) adding `metadata.google.internal` to `/etc/hosts`, and then not removing it when the real DHCP server is queried again.  We don't ship that script.  A rogue DHCP reply could override the DNS server instead, but presumably that would be undone when the real DHCP server is allowed to take over.

**Comment by travier** [comment]
> A rogue DHCP reply could override the DNS server instead, but presumably that would be undone when the real DHCP server is allowed to take over.

But that may not apply to the first boot initrd context as we only wait for the first DHCP answer and exit in NetworkManager.

**Comment by bgilbert** [comment]
The design of this particular exploit allows the rogue DHCP response to not have to guess a correct network configuration; it can configure something invalid.  In the one-shot initrd case, that'll cause us to simply fail.  But if the exploit can be upgraded to send a correct network configuration and a rogue DNS server, it would succeed both in the initrd and real-root case.

It might make sense to switch both Ignition and Afterburn to hardcoding the IP address, to avoid this class of problems altogether.

**Comment by cgwalters** [comment]
One thing tangentially related to this I mentioned elsewhere - I believe it would work for us to redo our networking setup such that we only bring up link-local networking (i.e. no DHCP requests) to fetch from the metadata server, and only then bring up full networking in the initramfs if needed to fulfill remote Ignition configs.  That would comprehensively close all forms of this flaw.

**Comment by bgilbert** [comment]
@cgwalters That staged design would also help with DigitalOcean support, since the public IP address is only available from their link-local service over HTTP.

**Comment by darkmuggle** [comment]
The Cloud-init DigitalOcean provider does not rely on DHCP at all -- it uses the `ip4LL`  and actually sets it up:
https://github.com/canonical/cloud-init/blob/6e0aa175513d0d5f64a3684f6840621cb9759b27/cloudinit/sources/helpers/digitalocean.py

**Comment by cgwalters** [comment]
> The Cloud-init DigitalOcean provider does not rely on DHCP at all -- it uses the ip4LL and actually sets it up:

Ah right, that's because DO basically *requires* using their metadata server for networking, i.e. it doesn't support DHCP right?  (Hopefully we don't still try and fail to do DHCP there)

**Comment by bgilbert** [comment]
Right.  We currently don't support that environment at all, except for "custom image" mode where DHCP does work.

**Comment by darkmuggle** [comment]
The crux of the attach is based on the `xid` or the transaction id. NetworkManager sets the `xid` [1] via [2]. 

The vulnerability, which is specific to ISC DHCP client [3] allows for brute-forcing the XID since one element is knowable, and the other two time and PID elements are predictable.  NetworkManager uses random seed entropy, which is not knowable to an attacker, to generate a random 32bit integer for the transaction id.  Of course we should confirm with the NM folks, but I think its unlikely that NM has the same attack vector.

[1] https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/main/src/n-dhcp4/src/n-dhcp4-c-connection.c#L1024
[2] https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/main/src/n-dhcp4/src/n-dhcp4-c-connection.c#L1024
[3] https://github.com/irsl/gcp-dhcp-takeover-code-exec#the-vulnerability

**Comment by bengal** [comment]
n-dhcp4 (the DHCP client corresponding to `dhcp=internal` in NM) initializes the RNG with a seed [1] derived from a combination of `getauxval(AT_RANDOM)`, the current time and the configuration address in the heap.

AT_RANDOM is supplied by kernel, I suspect it shouldn't be predictable (but I am not familiar with how it's generated). 

Provided that address randomization is enabled (`cat
/proc/sys/kernel/randomize_va_space`), the config address should also be unpredictable,  but this again depends on kernel.

[1] https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/main/src/n-dhcp4/src/n-dhcp4-c-probe.c#L345-362

**Comment by jlebon** [comment]
We discussed this in the [community meeting](https://meetbot-raw.fedoraproject.org/teams/fedora_coreos_meeting/fedora_coreos_meeting.2021-06-30-16.29.txt) today.

From the comments above, it sounds like FCOS and particularly NM is not affected by this, so we should be fine. Though there was a suggestion that it may still be worth moving Ignition and Afterburn to use IP addresses rather than a hostname for the metadata server (@bgilbert will file a separate ticket for that).

@bengal From your side, is there more investigation to be done here, or can we close this? Has the Security Team looked at it as well (or do they plan to)?

**Comment by darkmuggle** [comment]
ASLR is enabled on Fedora by default (and by default on a modern kernel). So unless `aarch64` has a different config, then I'm inclined to say this is resolved. @dustymabe since you have access to `aarch64` builds can I bother you for confirmation?
```
[core@cosa-devsh ~]$ cat /proc/sys/kernel/randomize_va_space
2
```

**Comment by cgwalters** [comment]
I would agree that strong entropy *mitigates* this but I don't consider that a *fix*.  We should not allow a network attacker to execute arbitrary code, even if they happen to get lucky.

Or I guess in practice, "execute arbitrary code" should only be possible when breaking the equivalent of e.g. sha256 hash.  32 bits of entropy != sha256 level of difficulty.

**Comment by cgwalters** [comment]
Also the comment there in the NM source even says it:

> Again, none of these are meant as security measure, but only to * avoid *ACCIDENTAL* seed clashes.

If we're treating this as part of a security boundary, then it would make sense to use cryptographic level entropy, e.g. from [OpenSSL RAND_Bytes()](https://www.openssl.org/docs/man1.1.1/man3/RAND_bytes.html) or equivalent as it's effectively acting as a key or secret.

But I don't think we should make this part of a security boundary.  Cryptographic entropy would just strengthen the mitigation - the comprehensive *fix* is to not allow DHCP requests to potentially get lucky and execute arbitrary code.

Or stated yet another way, if I provision a FCOS system and provide SSH keys, I expect that "execute arbitrary code over the network" is solely a function of something like a `sshd` flaw, a leaked key, or really horrible cases like a flaw in the kernel networking stack, not a flaw in the DHCP client.

**Comment by dustymabe** [comment]
> ASLR is enabled on Fedora by default (and by default on a modern kernel). So unless `aarch64` has a different config, then I'm inclined to say this is resolved. @dustymabe since you have access to `aarch64` builds can I bother you for confirmation?
> 
> ```
> [core@cosa-devsh ~]$ cat /proc/sys/kernel/randomize_va_space
> 2
> ```

```
[core@rpi4 coreos-assembler]$ cat /proc/sys/kernel/randomize_va_space
2
[core@rpi4 coreos-assembler]$ rpm-ostree status 
State: idle
Deployments:
● ostree://fedora:fedora/aarch64/coreos/testing-devel
                   Version: 34.20210615.dev.1 (2021-06-15T16:00:07Z)
                BaseCommit: bc0e38262d392f75d5c65cd9dab8f1da8a72a93c5297b55d726c2ce2c88d5f15
              GPGSignature: (unsigned)
           LayeredPackages: NetworkManager-wifi systemd-oomd-defaults

  ostree://fedora:fedora/aarch64/coreos/testing-devel
                   Version: 34.20210615.dev.1 (2021-06-15T16:00:07Z)
                    Commit: bc0e38262d392f75d5c65cd9dab8f1da8a72a93c5297b55d726c2ce2c88d5f15
              GPGSignature: (unsigned)
```

**Comment by bgilbert** [comment]
Again, as I understand it, we're not affected by this specific exploit because we don't ship `google_set_hostname`.

**Comment by cgwalters** [comment]
> Again, as I understand it, we're not affected by this specific exploit because we don't ship google_set_hostname.

Hmm.  At some point someone is going to need to try to reproduce this, probably by hacking NM to produce easily predictable `xids`.

OK there original page links to https://gitlab.com/gitlab-com/gl-security/security-operations/gl-redteam/red-team-tech-notes/-/tree/master/oslogin-privesc-june-2020#privilege-escalation-via-metadata-server-hijacking-cve-2020-8903
which seems to really be where this was found.

However, reading that what I don't understand here is - isn't the DHCP server in control over which DNS servers are used too and hence be able to change the meaning of `metadata.google.internal` that privileged software uses as a base?

I guess my bottom line here is: It does seem likely we are less vulnerable or potentially not even vulnerable due to missing that hook, but I still think we should remove *all potential for vulnerability* here by not using DNS.  

Hmm wait and from this section in that text:

> It will then begin flooding the local host with DHCP ACK packets that contain that xid

Is that really possible that a local, unprivileged user can inject a DHCP ACK packet?  That seems like a potentially widespread problem if so.

**Comment by bgilbert** [comment]
> However, reading that what I don't understand here is - isn't the DHCP server in control over which DNS servers are used too and hence be able to change the meaning of metadata.google.internal that privileged software uses as a base?

Sure, but this particular exploit doesn't need to correctly configure networking on the node.  The spoofed DHCP response has a non-functioning network config, a poisoned IP address for the metadata service, and a 15-second lease.  When the lease expires, dhclient obtains a proper lease but doesn't remove the poisoned hosts entry.  If the exploit used a poisoned DNS server, it would also need to configure the target's networking correctly.

**Comment by cgwalters** [comment]
>  If the exploit used a poisoned DNS server, it would also need to configure the target's networking correctly.

What's hard about that?  In this case the attacker has read-only access to the system journal (which is how they were getting the `xid` easily, NM was apparently actively logging it in earlier versions) they can also get all the information from the original DHCP response.

(Now, another way in which this doesn't really apply to us is that I believe it's an Ubuntu-ism to have "unprivileged user in the `adm` group but without `sudo`".  On the other hand, on FCOS we *do* explicitly add the user to those groups for the same reason, so a FCOS administrator might reasonably assume they could remove the `sudo` group from `core` to have "read-only sysadmin" and be vulnerable too)

**Comment by bgilbert** [comment]
> In this case the attacker has read-only access to the system journal (which is how they were getting the xid easily, NM was apparently actively logging it in earlier versions) they can also get all the information from the original DHCP response.

They do not.  The writeup specifically says that the XIDs are guessed.

**Comment by darkmuggle** [comment]
Google is working the problem [1].

Part of the contract with public cloud is that you can trust the provider. DHCP is done at the link layer (i.e. privileged) of the networking. Pretty much every cloud image relies on this trust existing.  The exploit takes advantage of this trust.

Switching to IP's is a sensible solution, but the documented API's use the DNS name. It would be nice if GCP had SSL protected meta-data or documented that that we could assume the IP `169.254.169.254` is stable. But that's not the case now and for that reason, any reaction would be hasty.

[1] https://www.securityweek.com/google-working-patching-gcp-vulnerability-allows-vm-takeover

**Comment by cgwalters** [comment]
> They do not. The writeup specifically says that the XIDs are guessed.

OK I know this whole topic is confusing.  I'm talking about https://gitlab.com/gitlab-com/gl-security/security-operations/gl-redteam/red-team-tech-notes/-/tree/master/oslogin-privesc-june-2020#privilege-escalation-via-metadata-server-hijacking-cve-2020-8903
which is the "exploit via local user" path, not the "exploit via internet" path that came up originally.

Specifically see:

> Compute instances in GCP use DHCP to configure their network interface. Seven of the images that Google provides implement the dhclient binary in such a way that the DHCP transaction ID (aka xid) is recorded in system logs.

However, in FCOS we don't use `dhclient`, we use the `dhcp=internal`, see also https://bugzilla.redhat.com/show_bug.cgi?id=1204226 (but ah right, this [used to differ for RHCOS](https://bugzilla.redhat.com/show_bug.cgi?id=1908462)).

**Comment by cgwalters** [comment]
I was playing around to see if I can send packets to NM from an unprivileged user, some notes so far:

- [the systemd dhcp code uses a BPF filter](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/30940222ccb31d15ab685d48c3721ecfb68b73e3/src/libnm-systemd-core/src/libsystemd-network/dhcp-network.c#L30) that rejects anything that doesn't look like a DHCP packet in the kernel, before even getting to userspace
- The code (sensibly) explicitly only holds the socket open while performing DHCP, not while idling

**Comment by bengal** [comment]
>     * the systemd dhcp code uses a BPF filter

Note that since NM 1.22, `dhcp=internal` no longer uses the systemd implementation, but it uses the one from [n-dhcp4](https://github.com/nettools/n-dhcp4). Since n-dhcp4 is not packaged as library yet, it's included in NM sources: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/1.32.2/src/n-dhcp4/src/n-dhcp4-socket.c#L36

**Comment by bgilbert** [comment]
Filed https://github.com/coreos/fedora-coreos-tracker/issues/891 to discuss mitigating this class of exploit on GCP.

**Comment by travier** [comment]
#891 is a nice summary of the discussion. Closing this one but feel free to re-open if you think something is missing from the analysis.
