### ISSUE TITLE
Ignition kargs helper should succeed on live systems if kargs are already correct

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#917]
The Ignition `kernelArguments` helper currently fails on live systems, since we have no way to change the kargs there.  However, if the specified kernel arguments are already set (`shouldExist` args exist and `shouldNotExist` args don't), it should succeed.

**Comment by lump** [comment]
Maybe the error could be more informative, too.  Right now, if you declare kernelArguments on a machine booted from PXE, the error from ignition-kargs-helper is:

```
lsblk: /dev/disk/by-label/boot: not a block device
Error: "lsblk" "--pairs" "--paths" "--output" "NAME,LABEL,FSTYPE,TYPE,MMOUNTPOINT,UUID" "/dev/disk/by-label/boot" "--nodeps" failed with exit status: 32
```

And the error from ignition gives the generic message asking that you ensure your config is valid.

**Comment by dustymabe** [comment]
>  However, if the specified kernel arguments are already set (`shouldExist` args exist and `shouldNotExist` args don't), it should succeed.

👍

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `35.20211119.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `35.20211119.3.0`.

**Comment by lump** [comment]
I can confirm that it does no longer puke if the kernel arguments match.

The error message is still pretty generic though.  This is what it looks like if the kernel flags don't match.  The only clue is:

```Displaying logs from failed units: ignition-kargs.service```

![image](https://user-images.githubusercontent.com/280484/145493024-ea8bf280-69b1-4b41-a4c7-996d24cb1083.png)

**Comment by bgilbert** [comment]
It [should say](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/05core/usr/lib/dracut/modules.d/35coreos-ignition/coreos-kargs.sh) `Need to modify kernel arguments, but cannot affect live system`.  Have you checked the logs for `ignition-kargs.service`?

**Comment by lump** [comment]
It just doesn't show the main error on the console by default, but I'm okay with that because that's how most other ignition errors behave.  I think it can't be seen on the console because what is shown is only the very bottom of a verbose dump of the ignition JSON.

What shows up on the console seems to be the same dump as systemctl status:
`systemctl status igintion-kargs | cat`
![image](https://user-images.githubusercontent.com/280484/145497359-21517808-577d-4a14-ac82-f68054c6506b.png)

The real error can be found if you enter the rescue shell and look at the top and scroll all the way over the right, the error is there.  At least the error shows up red so you get the clue that you need to scroll to the right.

Top of `journalctl -u ignition-kargs`
![image](https://user-images.githubusercontent.com/280484/145497599-1b4f0686-0f93-4385-8553-298d45e8a4e1.png)

Scrolled to the right 19 pages:
![image](https://user-images.githubusercontent.com/280484/145497682-e7b5465d-53b1-4b75-9825-49aeffa44f4a.png)
